### ISSUE TITLE
The import statement doesn't recognise the / (Slash) for CPP target.

### ISSUE THREAD

**Issue by debashisbd** [icyphy/lingua-franca#102]
The import statement doesn't recognise the / (Slash) for CPP target. For CPP target import from another folder or directory is not working.
Please check the screenshot.
![Screenshot from 2020-02-03 15-21-03](https://user-images.githubusercontent.com/58014025/73660973-88f63980-4699-11ea-9c02-7f8162d3bd6f.png)

**Comment by lhstrh** [comment]
Thanks for reporting this! 

The grammar currently has a dotted FQN (as is used in Java) as allowable strings for imports. For languages without a class path this is problematic, so we could change the grammar to accept paths as well. One problem is that the separators used in paths are platform dependent, and we don't want an LF file written and successfully compiled on one platform to throw errors on another. We can get around this by allowing both `/` and `\` as separators and replacing them according to the platform on which the compilation takes place. This would break cross-compilation, but that doesn't seem a very common use case, anyway, and we could overcome the issue by adding a target property or `lfc` flag for explicitly specifying the platform. Unless anyone watching this thread disagrees with this approach, I'll go ahead and implement it...

**Comment by edwardalee** [comment]
If we allow paths, we will also have allow spaces.
Another alternative is just to quote the import:
    import “foo/bar.h”;

**Comment by cmnrd** [comment]
Ahh, I see. I immediately assumed that this is a problem with the way the C++ backend handles imports without looking back at the grammar. I am actually fine with using the dot separator for lf imports. Since the lf compiler has full control over the imports it can easily handle them across platforms. I am not sure why this would be problematic if the target language does not have a classpath.

It is another issue when we are talking about target language imports. I am not sure what the current status of this discussion is, but for this we currently rely on the target language compiler, right? It would only be problematic if there is an LF statement that allows to import target language code.

**Comment by lhstrh** [comment]
Not all valid paths translate into a valid FQN by substituting the dots with the OS's path separator, so I really think we need to treat FQNs and paths/filenames separately. The possibility of including target language code that you raise relates to our unresolved discussion #32 regarding `preamble`. Perhaps now is a good time to revisit the issue and try to come to an agreement?

**Comment by cmnrd** [comment]
> we need to treat FQNs and paths/filenames separately
Agreed. My point is that I don't think LF should support path based imports. We have full control over how LF imports work and how FQNs translate to file paths. Therefore, LF can have its own import system with its own rules. How the compiler translates importrs to FS lookups can then depend on the platform (if that is needed).

**Comment by cmnrd** [comment]
@lhstrh Can we close this? I am not exactly sure what the status of the discussion is. If there are still issues for discussion, we should probably move it to a more genral issue.

**Comment by lhstrh** [comment]
Still got this on my to do. Let's keep it open for now.

**Comment by lhstrh** [comment]
Fixed in https://github.com/icyphy/lingua-franca/commit/f13525ca31232f099259d59caa29605003f90dd1.
