### ISSUE TITLE
Comments in Lingua Franca grammar

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#104]
While working on some examples, I realized that it is not possible to comment LF code. I think comments would be very convinient to have. Probably we should also think about introducing a mechanism for documentation directly into the language. I have something similar to Python's docstrings in mind.

**Comment by edwardalee** [comment]
??? I put comments in the Lingua Franca code all the time...

**Comment by cmnrd** [comment]
Oh, I didn't realize that this works already. I was looking into the grammar, but didn't find any rule about comments. Apparently, this is handled by xtext automatically.
