### ISSUE TITLE
Add a flag to lfc to only generate e.g. C outputs but not run the target compiler

### ISSUE THREAD

**Issue by edwardcwang** [icyphy/lingua-franca#109]
Currently e.g. say if the reactor contains platform/target-specific code, it's not ideal to have to ignore the error from invoking the system C compiler just to get the generated C output.

**Comment by lhstrh** [comment]
I agree this is useful for debugging in the early stages. Once we've established a target (say FlexPRET), we should associate it with customized compiler options, etc. Any suggestions for what to call the flag?

**Comment by edwardcwang** [comment]
Maybe for now `-raw` or `-no-compile` or something like that?

**Comment by lhstrh** [comment]
https://github.com/icyphy/lingua-franca/wiki/Downloading-and-Building#lfc
