### ISSUE TITLE
Target property for Endianness

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#113]
The bit-wise arithmetic performed in the C backend currently assumes Little Endian, but we might at some point want to target architectures that are Big Endian. To support these, we'll need to introduce a target property to indicate Endianness.

**Comment by mew2ub** [comment]
I'm not sure specifically what part of the code you're referring to, but my understanding of how C works is that endianness should already be abstracted away. See https://stackoverflow.com/questions/1041554/bitwise-operators-and-endianness.

**Comment by lhstrh** [comment]
On second thought, the compiler outputs constants that will be laid out in memory accordingly, so this can be ignored.
