### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by MattEWeber** [icyphy/lingua-franca#115]
Marten and I have been discussing implementing performance benchmarks for our targets. Marten referred me to this paper http://aleksandar-prokopec.com/resources/docs/reactor-scheduler.pdf (coincidentally also named "reactors") which has a variety of sample benchmarks, and I followed the citation trail to the Savina Suite of actor benchmarks https://shamsimam.github.io/papers/2014-agere-savina.pdf. The Savina Suite is intended to be a standard set of actor benchmarks designed to stress different aspects of actor implementations. To try them out, I implemented the first 4 benchmarks from the paper in TypeScript and added them to the repo at /lingua-franca/xtext/org.icyphy.linguafranca/src/benchmark/. It seems promising.

I think we should try to implement as much of the suite as we can for each of the targets. In the short term, I'm going to write more benchmarks for TypeScript. Perhaps, longer term, we can also add a script to automatically run all the benchmarks, similar to run-lf-test.

**Comment by lhstrh** [comment]
I'm tempted to say these benchmarks are better put in the reactor-ts repo and we run them with an `npm` command. Folks interested in using reactor-ts as a framework (sans LF) would also be interested in benchmarks, so putting them there might be better...

**Comment by mew2ub** [comment]
That's certainly an option. We could also have the benchmarks in multiple locations once we get them polished. 

The reason I picked src/benchmark/ was because it mirrors the structure of the LF test directories. The LF tests are at src/test/C, src/test/Cpp, and src/test/TS. I envision the benchmarks being organized in src/benchmark/C, src/benchmark/Cpp, and src/benchmark/TS.

**Comment by schoeberl** [comment]
Benchmarks for LF and reactors is for sure a very good idea! We are too often missing applications and benchmarks for the evaluation section of a paper.

Greetings from locked down Vienna,
Martin

**Comment by cmnrd** [comment]
Closing this. We have an almost complete implementation of the Savina suite now (see #406 for instance).
