### ISSUE TITLE
Missing KIELER installation instructions for building tutorial

### ISSUE THREAD

**Issue by mkuo005** [icyphy/lingua-franca#117]
The tutorial for building the IDE seems to be missing the instructions to install Kieler
https://github.com/icyphy/lingua-franca/wiki/Downloading-and-Building#building-the-ide

On the tutorial it says you will get 5 projects however when following the tutorial I got 6 projects.
One of the projects gets a build error unless Kieler is installed to Eclipse.

**Comment by lhstrh** [comment]
Thanks for pointing this out!
