### ISSUE TITLE
Grammar does not support hyphen in target property identifiers

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#126]
Currently, we have the `no-compile` property that uses a hyphen in its name. Marten also suggested renaming `cmake_include` to `cmake-include` (see #122). However, such names are currently not supported by the LF grammar. The left hand side of the key value pair is a Xtext ID which is not allowed to contain a hyphen. Therefore, the `no-compile` property is not usable at the moment.

This is also a problem with regard to being fully compliant with yaml. It appears that YAML supports hyphen in its keys (although people seem to prefer underscore).

**Comment by lhstrh** [comment]
Ah, thanks for spotting this! The reason I prefer the hyphen over the underscore is that this looks better when used as flags in CLI arguments. For instance, `lfc` has the flag `--no-compile`, which I think is preferable over `--no_compile`. I'll have a look at the grammar.

**Comment by edwardalee** [comment]
For this example, I would opt for "nocompile".

**Comment by lhstrh** [comment]
Why? Since “no” and “compile” are separate words, one would write “noCompile” in Camel case, “no-compile” in Kebab case, etc... I noticed we also have “keepalive”, but that word has been adopted as a noun as well... I still think “keep-alive” is more proper since we use it as an imperative.
