### ISSUE TITLE
Grammar rules for state with and without parameters

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#127]
While revisiting the code generation for state in C++ today, I noticed that the grammar rules behave somewhat unexpected (at least to me).

This is the current `ParameterizedState.lf` test for C++:
```
reactor Foo(bar:int(42)) {
    state baz:int(bar);
    reaction (startup) {=
        std::cout << "Baz: " << bar << std::endl;
    =}
}
main reactor ParameterizedState {
    a = new Foo();
}
```
There is a subtle issue here. Because the state variable `baz` has a type, its initialization is not recognized as a parameter but instead matches the `(':' type=Type) '(' value=(Literal | ID) ')'` rule. The generated C++ code is still correct, since the value `bar` is placed unmodified in the output code. If we change the line to `state baz(bar)` the parser correctly recognizes the parameter reference. The change here is subtle, but I believe there is a fundamental difference in the meaning of the two rules.

Is there a good reason to allow both Literal and ID in this rule `(':' type=Type) '(' value=(Literal | ID) ')'`? I think it would be clearer if the value can only be a literal. Then the programmer would be forced to use state declaration without a type if the initializer is a parameter reference.

**Comment by lhstrh** [comment]
You're right, this needs adjustment. I'm working on changes.

**Comment by cmnrd** [comment]
I am not sure if you plan to do further changes, but with the changes so far I still think some things are strange.

For instance, I can write this without any errors:
```
reactor Test(t:time(42)) { 
  // ...
}
```
Or if you consider this reactor:
```
reactor Test(foo:int(42), bar:time(20 msecs)) {
  // ...
}
```
I can write `state bar(foo);`, `state bar:int(foo);` or `state bar:double(foo)` which all makes sense (in the last case there is an implicit cast from in to double), but I cannot write `state offset:time(t);`. It only works without the explicit type (`state offset(t);`), which I think is inconsistent. Morever, I can still write `state offset:time(42);`

I think there is an underlying problem here and I believe it lies within the grammar rule for `TimeOrValue`. This rule is used in many places, but often it is used in a context where we precisely know whether to expect a time or a value. I will lineout a suggestion below that would help to eliminate the TimeOrValue rule.

I think it would be helpful to inroduce a dedicated rule for time:
```
Time: '0' | value=INT unit=TimeUnit;
```
This avoids any need to check time values in the validator. Only 0 or an integer followed by a unit are valid Times. Further we can introduce this rule:
```
TimeOrParameter: time=Time | parameter=[Parameter];
```
Here the validator should check that the referenced parameter has the type `time`. This rule could then be used wherever a time is required. For instance:
```
Timer:  'timer' name=ID ('(' offset=TimeOrParameter (',' period=TimeOrParameter)? ')')? ';';
```
We can also use it in the State rule:
```
State:
    'state' name=ID 
    (
        (':' ofTimeType?='time' '(' time=TimeOrParameter ')') | 
        (
            (':' type=Type)? ('(' init=LiteralOrCode | parameter=[Parameter] ')' )?
        )
    ) ';';

```
Finally we can adjust the Assignment, which is the only place where we truly expect a time or a value:
```
Assignment:
    (lhs=[Parameter] '=' time=Time, paramteter=[Parameter], value=LiteralOrCode);
``` 
I am not 100% familiar with the Xtext syntax, so the above rules could be broken, but you can probably see what I mean. All in all this should allow consistent use of time, values and parameters across Lingua Franca. Do you think changing the grammar like I outlined makes sense, or is there an issue with it that I do not see?

**Comment by edwardalee** [comment]
I suggest adding some tests for these patterns and trying it.  That’s really the only way to proceed.

**Comment by lhstrh** [comment]
I'm aware of these problems and I'm still working on this. My previous commits were predominantly to achieve tokenization of target code...

**Comment by cmnrd** [comment]
Alright. I wasn't sure what exactly your plan is. Looking forward to the changes then :)

**Comment by lhstrh** [comment]
More on this: over time I've come to realize that it is better to be more permissive in the grammar and add checks during validation rather than to make the grammar "water tight" on its own. The reason for this is two-fold: 1) avoiding the need to craft complex grammar rules makes it easier to let the grammar evolve as we introduce more features; and 2) the automatic error reporting from syntax violations is rather obtuse. Issues such as not providing units is more of a semantic issue than a syntactic one, anyway, and we can provide a much more detailed and informative error message if we treat them as such (through checks in the validator). I had also thought of the `Time: '0' | value=INT unit=TimeUnit;` production, but opted against it for this for this reason.

**Comment by lhstrh** [comment]
After my upcoming changes (not ready to push to master yet), the following code will be valid:
```
target C;

reactor Foo(x:int(0), 
	y:time(0), 			// units are missing but not required
	z(1 msec), 			// type is missing but not required
	p:int[](1, 2, 3, 4),		// list of integers 
	q:interval_t[](1 msec, 2 msec, 3 msec),	// list of time values
	r:time({=0=}),			// zero-valued target code also is a valid time
	g:time[](1 msec, 2 msec)	// list of time values
) {
	state s:time(y); 	// Reference to explicitly typed time parameter
	state t:time(z); 	// Reference to implicitly typed time parameter
	state v:bool; 		// Uninitialized state variable
}
```
and the following will be invalid:
```
reactor Bar(t:time(42), 	// ERROR: units missing
	x:int(0),
	h:time("bla"), 		// ERROR: not a type 
	q:time(1 msec, 2 msec)  // ERROR: not a list
) {
	state offset:time(42); 	// ERROR: units missing
	state w:time(x);	// ERROR: parameter is not a time
	state foo:time("bla")	// ERROR: assigned value not a time
}
```
Are there any test cases I should add to these lists?

**Comment by cmnrd** [comment]
Looks good :+1:

 Will it be possible to have state variables that inherit the type from the parameter? Something like this:
```
state x(p); // implicit type int[]
state period(z); // implicit type time
``` 

I am also wondering what happens in the case of `reactor X(t(0)) { ... }`. Whould this be valid code? What type would `t` have?

Is there any type checking done in this case `q:interval_t[](1 msec, 2 msec, 3 msec)`? Or is this left to the target compiler? I think proper typechecking would be very difficult to do for general C/C++. Would it be possible to assign `q` to a time state like this `state x:time[](q);`?

**Comment by lhstrh** [comment]
Comments inline below...
> Will it be possible to have state variables that inherit the type from the parameter? Something like this:
> 
> ```
> state x(p); // implicit type int[]
> state period(z); // implicit type time
> ```
Yes, these are valid.
 
> I am also wondering what happens in the case of `reactor X(t(0)) { ... }`. Whould this be valid code? What type would `t` have?

This would not be valid because a type declaration is missing. You can leave off the type only if it is initialized as a time with units (and the units can be left off if it is zero, but _only_ if the parameter is explicitly declared to be a `time`).
 
> Is there any type checking done in this case `q:interval_t[](1 msec, 2 msec, 3 msec)`? Or is this left to the target compiler?

It is left to the target compiler because the type is a target type.

> I think proper typechecking would be very difficult to do for general C/C++.

Right; we delegate this responsibility to the target compiler.

> Would it be possible to assign `q` to a time state like this `state x:time[](q);`?

Yes, it would be, in which case it _will_ be checked that all elements are valid times.

**Comment by lhstrh** [comment]
Done. Also see [NativeListsAndTimes.lf](https://github.com/icyphy/lingua-franca/blob/master/test/C/NativeListsAndTimes.lf).
