### ISSUE TITLE
Offsets on physical actions

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#129]
I would like to change how offsets are interpreted for physical actions.  The current specification says this:

    If the physical keyword is given, then the physical clock on the local platform
    is used to assign a timestamp to the action by the schedule function function
    as follows. First, let T be the larger of the current physical time and the current
    logical time (plus one microstep). The current logical time is the largest logical
    time at which the reactor owning the action has either reacted to something
    or has explicitly not reacted to something because no enabled events were
    relevant to it. Then min_delay and the offset argument to schedule function
    are added to T.

I would like to change it to this:

    If the physical keyword is given, then the physical clock on the local platform
    affects the timestamp of the action as follows. First, let total_offset be the sum
    of the min_delay of the action plus the offset argument to schedule() function.
    Then the assigned timestamp will be the larger of the current physical time and
    the current logical time plus the offset. The current logical time is the largest
    logical time at which the reactor owning the action has either reacted to
    something or has explicitly not reacted to something because no enabled
    events were relevant to it."

The difference is subtle, but important.  First, there is no difference when the total_offset is zero. The assigned timestamp in this case will always be the current physical time because current_logical_time will always lag physical time. Second, physical actions will be seen sooner (in physical time) by the LF program because the timestamp will be delayed (in physical time) *at most* by the total offset rather than *at least* by the total offset. Third, the logical time delay of a physical action will be *at least* the total offset, rather than *at most*.

We can state this as a principle: Do things as early as possible in physical time subject to always satisfying logical time constraints.

But the biggest advantage is yet to come:

When the total_offset is non-zero, we get a very nice property: The new policy gives us the possibility for much more deterministic programs, including the "poor man's Ptides," like what is described in Christian's DATE paper.

Specifically, if the total_offset is large enough that we *always* get current_logical_time + total_offset >= physical_time, then the timestamp will deterministically relate to current logical time.  Here are two important use cases:

1. A periodic task that is occasionally modified by a sporadic sensor. If total_offset = period, then the timestamp of the periodic sensor will *always* align with the periodic events.  This is guaranteed by the single mutex lock in our C implementation.  This gives us a huge improvement over polling, but preserves the determinism of polling!

2. "Poor man's Ptides:"  Federate A sends a message to federate B carrying timestamp T (the logical time of the message at the sender).  Federate B uses a physical action with total_offset F to receive the message.  If the following condition is satisfied, then the timestamp at the receiving end will *always* be T+F:
        F > D + L + E
    where D is the deadline at the sender's network interface, L is a bound on the network latency (including the sending and receiving software's execution times), and E is the bound on the clock synchronization error.

In any given setup, you can measure the setup to estimate what D+L+E should be.  Just set the total_offset to zero, and the difference between the payload timestamp and action timestamp is a minimum value for D+L+E.  Collect many such minima, and you have an experimental measure.  Choose the maximum of all these minima, perhaps with some additional safety margin. I'm doing that experiment right now using MQTT as the transport mechanism, and I'm finding that on my laptop, F = 10 MSEC is enough. I suspect a much lower number will be possible with our own transport mechanism.

There is one downside to this proposal: the HLA distributed scheduler won't work as well because it won't be able to take advantage of the min_delay parameter of physical actions (which corresponds to the "lookahead" in HLA).  I think this price is worth paying because HLA won't be very efficient anyway compared to Ptides.

**Comment by lhstrh** [comment]
This is a very interesting proposal. We had never really paid much attention to the combination of physical actions and delays because, from the face of it, there is usually little advantage to further delaying in physical time the handling of sporadic input; when we use physical actions we tend to assign them a delay of zero.

In the Ptides mechanism we detailed in the PLDI submission, we use an additional (variable) logical delay to ensure that the received message is injected at `T+F`. What this proposal effectively does is substitute the "useless" delay of physical actions with one that _is_ useful, allowing us to simplify our Ptides implementation by no longer requiring that the physical action be daisy chained with a logical one. So, yes, this makes a lot of sense to me.

I'm thinking this change also would not break any assumptions we have so far relied on in our work-in-progress on running reactions at different tags in parallel, since the change only pertains to scheduling of _physical_ actions...

**Comment by edwardalee** [comment]
It also occurs to me that with this new definition, physical actions become much easier to explain and to implement:

A physical action has a timestamp that is the larger of the current physical time and the time it would be assigned if it were a logical action.

Notice that this assures that we will satisfy the MIT, assuming it is satisfied for a logical action.

**Comment by edwardalee** [comment]
I have implemented this change. It caused no test failures, which just says that we weren't testing for the previous behavior anywhere.  This was probably the case because the previous behavior was so confusing that it wasn't clear how to make a test.
