### ISSUE TITLE
Gradle building entire src directory leads to build failure and inefficiency

### ISSUE THREAD

**Issue by mew2ub** [icyphy/lingua-franca#133]
I started getting this error when I tried to build the lfc jar file using our build-lfc script:

```
> Task :org.icyphy.linguafranca:shadowJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':org.icyphy.linguafranca:shadowJar'.
> shadow.org.apache.tools.zip.Zip64RequiredException: archive contains more than 65535 entries.
  
  To build this archive, please enable the zip64 extension.
  See: https://docs.gradle.org/5.4.1/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip:zip64

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 50s
```

I believe the problem is the multiple node_modules directories I have on my computer from running TypeScript reactors in `org.icyphy.linguafranca/src/benchmark`, `org.icyphy.linguafranca/src/example`, and `org.icyphy.linguafranca/src/test`. These node_modules directories are huge but you probably need more than one to get over that 65535 entry limit, which explains why I'm getting this problem and why the rest of you probably aren't if you don't have multiple instances of the node_modules directory.

But I don't think this is just a node_modules problem, I think it's unnecessary for our gradle build to be processing those directories (test, example, benchmark) at all. The configuration file for gradle sources for the the build is at `lingua-franca/xtext/gradle/source-layout.gradle`, and it indicates the entire src directory is being used to create the lfc jar file. We could speed up the build, reduce the size of the jar file, and get rid of this bug by excluding the unnecessary directories.

There are a few ways to do this:

1. I was successfully able to get my build to succeed again by editing source-layout.gradle to explicitly ignore all node_modules directories via

```
sourceSets.all {
	resources.exclude '**/*.g', '**/*.mwe2', '**/*.xtend', '**/*._trace', '**/node_modules' 
}
```

This doesn't remove the rest of the unnecessary directories from the jar, but it gets my build working again.

2. I also tried editing source-layout.gradle to only include the desirable directories, by changing the srcDirs (all of them in the file not just the one example below) from 

```
java.srcDirs = ['src', 'src-gen']
```

to

```
java.srcDirs = ['src/org', 'src/lib', 'src-gen']
```

The build finishes successfully (and much faster than normal), but the directory structure inside the jar file gets screwed up so the lib files are at a different location. Neither C, nor TypeScript reactors work because they can't find the libs (they are there in the jar though). If we want to go this route we could either figure out how to get gradle to produce the old directory structure or modify the code generators to work with the new locations.

3. We could sidestep the entire gradle configuration issue by just moving the test, example, and benchmark directories out of `org.icyphy.linguafranca/src/`. We'd have to modify the run-lf-tests script a little but I think that would be the only change.

**Comment by lhstrh** [comment]
I recall solving precisely this issue several months ago. I guess you changed the location where you put `node_modules` since then, but didn't update the exclusion path?

**Comment by lhstrh** [comment]
What I did at the time was simple remove the test directory from the jar (see: 49cace9b). We can simply add `'**/node_modules'` to that list.

However, I has also occurred to me that building has become gradually slower, so it's probably better to eliminate junk further upstream in the build process. I haven't looked at this very closely, but `'src/lib'` is not a java source directory; labeling it as such is probably what causes the reshuffling in the jar. Can we use something like `resources.include` instead?

**Comment by mew2ub** [comment]
The test directory's `node_modules` never left the test directory. Looking at https://github.com/icyphy/lingua-franca/commit/49cace9b5d637d7af5f9489e86ea493196ea3f3e, it looks like the issue is that newer src/benchmarks and src/examples directories were created later and they also have node_modules directories.

I agree upstream is better. I also prefer a solution that selects the specific files to build rather than a list of files to exclude that has to change whenever we add a new directory to src like the ones I suggested above. Do you have a preference over (1), (2), or (3)?

I'll look into `resources.include` for (2).
