### ISSUE TITLE
Code generation for after is broken

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#134]
While trying to implement code generation for the after keyword in C++, I realized that the code generation process is broken after the latest commits. The bodies of the two generated reactions are always empty. I assume this is because `generateDelayBody()` and `generateForwardBody()` produce a String, whereas the grammar now defines code as a series of tokens.

This problem did not show up in the tests because the generated reactors still compile and execute, but no data is delivered over the delayed connection and, therefore, no reactions are triggered. I think we will need a more complex test system, which validates the output of tests to find such errors in the future.

**Comment by lhstrh** [comment]
A fix is forthcoming.

**Comment by cmnrd** [comment]
Closing as it seems to be fixed by 82208d9
