### ISSUE TITLE
Kieler fails to install

### ISSUE THREAD

**Issue by cxbrooks** [icyphy/lingua-franca#140]
I'm having problems installing Kieler under Eclipse.

I created https://rtsys.informatik.uni-kiel.de/jira/browse/KIPRA-2035, but thought I should also report the issue here.

After the installation failed, I reproduced the problem as follows:

 First, I did:
`rm -rf ~/.eclipse ~/.p2 ~/.m2`

Then I installed Eclipse 2020-03 from the installer and selected "Eclipse for Java and DSL Developers," which includes Xtext.

Then,  followed the instructions at https://github.com/icyphy/lingua-franca/wiki/diagrams#enabling-diagram-synthesis 
Go to Help -> Install New Software -> Add Update Site
Add http://rtsys.informatik.uni-kiel.de/~kieler/updatesite/ 
Selected 
* Kieler Lightweight Diagrams Generic View
* Kieler Lightweight Diagrams Runtime
* Kieler Vector Graphics Export (now called KIELER Lightweight Diagrams Vector Graphics Export Powered by FreeHEP 2.1.1)

The installation failed, the following message dialog appeared:

> An error occurred while collecting items to be installed
> session context was:(profile=_Users_cxh_eclipse_dsl-2020-03_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.common,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.service,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph,0.6.1

I went back to Help -> Install New Software and in the Works with drop down, selected Elk 6.1, which corresponds with http://download.eclipse.org/elk/updates/releases/0.6.1/

It is not clear which things should be installed, so I selected:
* Eclipse Layout Kernel (Incubation) - Core components
* Eclipse Layout Kernel (Incubation) - Layout Algorithms
* Eclipse Layout Kernel (Incubation) - SDK

The following dialog appeared:

> An error occurred while collecting items to be installed
> session context was:(profile=_Users_cxh_eclipse_dsl-2020-03_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.common,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.common.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.debug,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.debug.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.force,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.force.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.mrtree,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.mrtree.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.radial,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.radial.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.rectpacking,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.rectpacking.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.spore,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.spore.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.algorithms.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.algorithms.feature.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ide,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ide.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ui,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ui.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.ui,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.ui.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.service,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.service.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.ui,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ide,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ide.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ui,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ui.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.sdk.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.sdk.feature.source,0.6.1

I tried reinstalling Elk 6.1, which corresponds with http://download.eclipse.org/elk/updates/releases/0.6.1/ and this time selected everything.

Again, the message was:

> An error occurred while collecting items to be installed
> session context was:(profile=_Users_cxh_eclipse_dsl-2020-03_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.common,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.common.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.debug,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.debug.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.force,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.force.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.dot,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.dot.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.layouter,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.layouter.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.mrtree,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.mrtree.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.radial,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.radial.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.rectpacking,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.rectpacking.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.spore,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.spore.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.algorithms.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.algorithms.feature.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.conn.gmf,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.conn.gmf.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.conn.graphiti,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.conn.graphiti.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ide,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ide.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ui,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ui.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.ui,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.ui.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.service,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.service.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.ui,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.ui.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.gmf.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.gmf.feature.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.json,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graph.json.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graph.json.feature.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.json.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ide,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ide.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.source,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ui,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ui.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphiti.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphiti.feature.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphviz.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphviz.feature.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.sdk.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.sdk.feature.source,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.ui.feature,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.ui.feature.source,0.6.1

**Comment by edwardalee** [comment]
I’ve cc’d Alex@Kiel hoping he can help...

Edward

---------
Edward A. Lee
EECS, UC Berkeley
eal@eecs.berkeley.edu
http://eecs.berkeley.edu/~eal

**Comment by a-sr** [comment]
I tried to reproduce the problem but Klighd and ELK were installed successfully.

Maybe the ELK update site was not available/online at that time?
I just updated some links in the update site, maybe this will help.

Could you please try again installing the Klighd features.
If the error occurs again could you please visit the ELK update site with your browser and report if it is available, so I can rule out that cause.

**Comment by a-sr** [comment]
Even if Klighd is successfully installed, the diagram plugin will report a compilation error because it is not yet compatible to the latest release but I will take care of that soon.

**Comment by a-sr** [comment]
PR #141 will provide compatibility to the latest release. I did not push the changes to the master because everyone else would have to update their eclipse too. I thought I would be better if it is done in a coordinated fashion.

**Comment by cxbrooks** [comment]
Thanks for taking a look.

I'm still getting the same message when I attempt to install as per my original message, thought I do now see the Batik version of the Vector Graphics Export.

Here's what I did:

I removed the .m2, .eclipse and .p2 directories, install a clean version of Eclipse 2020-03 for DSL Developers, created a new workspace, then did:

* Help -> Install New Software -> Add Update Site
  * As expected, none of the KIELER or ELK update sites are listed in the pull down.
* Add http://rtsys.informatik.uni-kiel.de/~kieler/updatesite/
* Under "KIELER Lightweight Diagrams", I selected
  * KIELER Lightweight Diagrams Generic View
  * KIELER Lightweight Diagrams Runtime
  * KIELER Lightweight Diagrams Vector Graphics Export Powered by Batik 1.6 (note that the wiki says "KIELER Vector Graphics Export", so it should be updated. There is also "KIELER Lightweight Diagrams Vector Graphics Export Powered by FreeHEP 2.1.1", should I select the Batik version or the FreeHep version

Installation proceeds, then I got:

> An error occurred while collecting items to be installed
> session context was:(profile=_Users_cxh_eclipse_dsl-2020-032_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.common,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.core.service,0.6.1
> No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature,0.6.1
> No repository found containing: osgi.bundle,org.eclipse.elk.graph,0.6.1

Back over in Help -> Install New Software, there are a number of new sites listed, including
* http://build.eclipse.org/modeling/elk/updates/0.6.0/
* http://download.eclipse.org/elk/updates/releases/0.6.0/
* http://download.eclipse.org/elk/updates/releases/0.6.1/

From my browser, I can get to all three of the above sites.

From within the Eclipse Available Software window, selecting each of the three update sites changes what is displayed under Eclipse Layout Kernel, for example, the 0.6.1 site (last URL above) shows a number of items that have a 0.6.1 version.

I tried selecting  http://download.eclipse.org/elk/updates/releases/0.6.1/ and then selected everything under Eclipse Layout Kernel, but got what appears to be the same message as what I initially reported

```
An error occurred while collecting items to be installed
session context was:(profile=_Users_cxh_eclipse_dsl-2020-032_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.elk.alg.common,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.common.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.debug,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.debug.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.disco.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.force,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.force.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.dot,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.dot.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.layouter,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.graphviz.layouter.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.mrtree,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.mrtree.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.radial,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.radial.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.rectpacking,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.rectpacking.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.spore,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.spore.source,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.algorithms.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.algorithms.feature.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.conn.gmf,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.conn.gmf.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.conn.graphiti,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.conn.graphiti.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ide,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ide.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ui,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.grandom.ui.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.debug.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.meta,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.ui,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.meta.ui.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.service,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.service.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.ui,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.ui.source,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature.source,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.gmf.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.gmf.feature.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.json,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graph.json.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graph.json.feature.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.json.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.text,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ide,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ide.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.source,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ui,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph.text.ui.source,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphiti.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphiti.feature.source,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphviz.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.graphviz.feature.source,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.sdk.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.sdk.feature.source,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.ui.feature,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.ui.feature.source,0.6.1
```

**Comment by a-sr** [comment]
One of my colleagues, the one who works on Klighd, was able to reproduce the error.
We still do not understand the origin of this problem but it seems Eclipse gets confused by the fact that ELK 0.6.1 is available while Klighd references 0.6.0. This does not explain why you could not install ELK 0.6.1 directly but nonetheless we can try out a possible solution. 

Could you please try to install the Klighd features using this update site: https://kieler.github.io/KLighD/
Either use a fresh Eclipse or make sure that you delete all kieler/klighd/elk update sites beforehand.
In the Install New Software... dialog click on Manage... to get to the list of all registered update sites and remove every update site that has _kieler_, _klighd_, or _elk_ in its URL.

I hope this will work.

**Comment by cxbrooks** [comment]
Thanks!  That worked.  
1. I did 
```
rm -rf ~/src/eclipse/dsl-2020-03/
rm -rf ~/.m2 ~/.p2 ~/.eclipse/
```
2. Reinstalled Eclipse 2020-03 for Java and DSL developers
3. Used  https://kieler.github.io/KLighD/ as an updated site
4. The software was unsigned, I clicked accept.
5. The install worked.

I now have two errors:
```
Description	Resource	Path	Location	Type
org.eclipse.elk.alg.layered.p4nodes.bk.EdgeStraighteningStrategy cannot be resolved to a type.	LinguaFrancaSynthesis.xtend	/org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis	line: 33 /org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis/LinguaFrancaSynthesis.xtend	Xtend Problem
The method or field EdgeStraighteningStrategy is undefined	LinguaFrancaSynthesis.xtend	/org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis	line: 81 /org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis/LinguaFrancaSynthesis.xtend	Xtend Problem
```

These would likely go away when Pull #141 is resolved.

To close this bug, either the repository listed at https://github.com/icyphy/lingua-franca/wiki/diagrams#enabling-diagram-synthesis needs to be updated or the page itself needs to be updated.  Also, the wiki is slightly incorrect, the name of one of the things to be installed is "KIELER Lightweight Diagrams Vector Graphics Export Powered by Batik 1.6"

**Comment by a-sr** [comment]
That's good news!
Yes, PR #141 will fix the compilation errors.

**Comment by a-sr** [comment]
The wiki should list the Klighd update site rather than the KIELER one. Since January, Klighd is a standalone project, hence it is best to use its update site directly. This way the other KIELER projects cannot interfere, as the now seem to do.

I can adjust the wiki. However, regarding PR #141, that means everyone has to register the new update site **and** make sure the old ones are deleted (as described in my previous comment). Otherwise, they will run into the same errors.

**Comment by a-sr** [comment]
Updated the [wiki page](https://github.com/icyphy/lingua-franca/wiki/diagrams#enabling-diagram-synthesis) to list the new update site and fixed the name of the SVG exporter package.

**Comment by edwardalee** [comment]
I just did a git pull, and I get thousands of build errors.
I tried updating Kieler, and I get the error below.
Do I really have to reinstall Eclipse from scratch???

Edward


An error occurred while collecting items to be installed
session context was:(profile=_Users_eal_eclipse_java-2018-12_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.elk.alg.common,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.alg.layered,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.core.service,0.6.1
No repository found containing: osgi.bundle,org.eclipse.elk.graph,0.6.1
No repository found containing: org.eclipse.update.feature,org.eclipse.elk.feature,0.6.1


———————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by a-sr** [comment]
I have not tried it but I think you do not need to create a new installation.
It seems you have to remove all the old kieler related update sites (as described [here](https://github.com/icyphy/lingua-franca/issues/140#issuecomment-610448114)) before you register the new one and update the dependencies.

**Comment by cxbrooks** [comment]
I had lots of errors under Eclipse, so I recreated the Eclipse project with File -> Import and the errors went away.

My Eclipse installation already had the new Kieler update sites setup.  However, the errors I was seeing did not seem to have anything to do with Kieler.

Perhaps one quick way to get rid of the old Kieler sites would be to do 

`rm -rf ~/.eclipse`

and/or

`rm -rf ~/.p2`

This is fairly similar to reinstalling Eclipse though.

Under Maven, I had to delete the contents of the xtend-src directories, then the maven build worked.  I updated the clean target in Maven, I'll submit a pull request shortly.

**Comment by edwardalee** [comment]
OK, this worked with one more detail. You have to restart Eclipse after removing the previous sites. So, in summary, this is what worked for me:
1. Help->Install New Software->Manage
2. Search for kieler, klighd, and elk and remove all matches.
3. **Restart Eclispse**
4. Help->Install New Software: Enter:  https://kieler.github.io/KLighD/, click Add, and Click Add again in the dialog that pops up.
5. Accept the license, and accept installing unsigned software.
