### ISSUE TITLE
Parameters to the main reactor

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#146]
I have seen some examples that use parameters on the main reactor and was a bit surprised because I am not aware of a mechanism to assign those parameters. Today I was thinking about a good mechanism for passing CLI arguments to a reactor instance and realized that the parameters on the main reactor could be used for that. In the C++ taget it shouln't be hard to automatically extend the CLI parser with custom arguments and pass those to the main reactor. This would work of course only for types that are supported by th CLI parser such as int, bool or string.

For example this program
```
main reactor Foo(int bar=42) {
  // ....
}
```
could be given any value `bar` on execution:
```
./bin/foo --bar 2
```

What do you think of this? Would this work in other targets as well?

**Comment by edwardalee** [comment]
Yes, this is a good idea.
We did this same thing with accessors.

Edward

———————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by mew2ub** [comment]
I had been thinking along similar lines. Not only would it be relatively
straightforward to support this in TypeScript, it should also be feasible
to automatically generate cli usage documentation for the main reactor
parameters.

**Comment by cmnrd** [comment]
This is now supported by the C++ target and I added a parser for the <value> <unit> format in order to support time parameters.

When #147 is resolved we should also add some tests for passing parameters via CLI arguments.

**Comment by cmnrd** [comment]
Closing this since it is implemented for C++ and we will not implement this for C. The aspect of testing is a separate issue (#508).
