### ISSUE TITLE
How does the logical time advance in Lingua Franca?

### ISSUE THREAD

**Issue by lhy673542630** [icyphy/lingua-franca#152]
Hi,
I am working on synchronous programming.
I am wondering how does the logical time advance in Lingua Franca.
Since logical time doesn't advance within one reaction, how would  logical time increase?

In my understanding, logical time will advance under the following conditions:
1. If there are some scheduled actions which will happen in the future.
2. If there are timers periodically triggering reactions.
3. If there are logic delays, such as "after" keyword.

However, the way that logical time advances is still not that clear.
Could you please explain it?
Thank you so much and I do like Lingua Franca very much!

Best regards

**Comment by edwardalee** [comment]
I have added the following paragraph to the [Overview](Overview#action-declaration) page. Hope this helps.

At the starting logical time, reactions that specify a **startup** trigger will execute. Also, any reactions that are triggered by a timer with a zero offset will execute. Any outputs produced by these reactions will have the same logical time and will trigger execution of any downstream reactions. Those downstream reactions will be invoked at the same logical time unless some connection to the downstream reactor uses the **after** keyword to specify a time delay. After all reactions at the starting logical time have completed, then time will advance to the logical time of the earliest next event. The earliest next event may be specified by a timer, by an **after** keyword on a connection, or by a [logical or physical action](Language-Specification#action-declaration). Once logical time advances, any reactions that are triggered by events at that logical will be invoked, as will any reactions triggered by outputs produced by those reactions.

**Comment by lhy673542630** [comment]
Hi,

helps a lot! It is now clear to me:).

Thanks and best regards
