### ISSUE TITLE
After introduces unexpected dependencies

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#154]
I encountered an issue with the way 'after' currently works. Consider the code below, consisting of a source and two workers. The workers are connected to the source via 'after' and the workers output is handled within two reactions of the main reactor.

```
target Cpp;

reactor Source {
    output out:unsigned;
    
    reaction(startup) -> out {=
        out.set(1);
    =}
}

reactor Work {
    input in:unsigned;
    output out:unsigned;
    
    reaction(in) -> out {=
        out.set(in.get());    
    =}
}

main reactor Parallel {
    s = new Source();
    w0 = new Work();
    w1 = new Work();
    
    s.out -> w0.in after 10 msec;
    s.out -> w1.in after 20 msec;
    
    reaction(w0.out) {=
        std::cout << "Received " << *w0.out.get() << " from worker 0\n";
    =}
    
    reaction(w1.out) {=
        std::cout << "Received " << *w1.out.get() << " from worker 1\n";
    =}
}
```

![Parallel](https://user-images.githubusercontent.com/6460123/80691251-472a3300-8ad0-11ea-84a8-6e576eb3772a.png)

The program certainly looks right and the LF IDE does not report any errors. But when compiling and executing, the runtime complains that there is a dependency cycle. Even worse, I was not able to find an ordering that would resolve the cycle. Indeed, there are multiple cycles:

![Screenshot_20200430_110812](https://user-images.githubusercontent.com/6460123/80693722-ba817400-8ad3-11ea-96fa-42d8e109c031.png)

Why is there a cycle? The after keyword introduces an action and two new reactions to the scope of the main reactor. Apart from the data dependencies between reactions, this also introduces new dependencies based on the ordering of reactions within the main reactor, but it is entirely intransparent how this happens. Those additional dependencies create the cycle in the above examples. I assume that both the validator and the graph tool work on the unmodified AST and therefore do not see the cycle.

I think that the after keyword should not introduce new reactions to the scope of the reactor. Instead, it should instantiate and connect a Delay reactor that contains the logical action and two reactions. This would eliminate the dependencies between delay reactions and the  already existing reactions, and only add the required data dependencies.

Even with this modification, the check for dependency cycles should operate on the modified AST.

**Comment by cmnrd** [comment]
There is another subtle nuance to this issue. The order of the two reactions in the delay reactor matters. In order to avoid dependencies propagating through the delay reactor, the reaction that writes the output should have a higher priority than the reaction that receives the input. This way, the delay output has no dependency on the delay input.
![ParallelDelay](https://user-images.githubusercontent.com/6460123/80696031-15689a80-8ad7-11ea-9d5a-7e96edef4914.png)

**Comment by edwardalee** [comment]
Yes, you are right. Your solution seems like the right one to me.

**Comment by lhstrh** [comment]
The downside of inserting a reactor rather than a pair of reactions is that, _without support for generics_, this will require adding a new class definition for each delay reactor (because the types of the ports need to match). In C++ and TypeScript we can generate a parameterized delay reactor, which makes the solution more elegant...

**Comment by edwardalee** [comment]
Right. This is why we did it that way in the first place. Presumably, the class definition can be code generated, right?

**Comment by lhstrh** [comment]
Yep -- I'm doing that.
