### ISSUE TITLE
MovingAverage TS test fails

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#155]
While looking at the log of this [build](https://travis-ci.com/github/icyphy/lingua-franca/builds/162909573), I found that one of the TS tests reports an error, but this error is not recognized by the test script:
```
Executing command:node MovingAverage/dist/MovingAverage.js
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Received: 0
Received: 0.25
Received: 0.75
Received: 1.5
Received: 2.5
Received: 3.5
Received: 4.5
ERROR: Expected undefined
Exception occurred in reaction: MovingAverage/p[R0]: Error: An unexpected error has occurred.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```
While there is clearly an error, the Test is not reported as failed.

**Comment by mew2ub** [comment]
Fixed. The test was failing because it was running in fast mode and blowing past the array of expected results. The test was failing silently because errors thrown in reactions were being caught in the runtime and not allowed to kill execution.
