### ISSUE TITLE
Reactions forms a cycle

### ISSUE THREAD

**Issue by lhy673542630** [icyphy/lingua-franca#160]
Hi, 

I am trying to use Ling Franca in control systems, where there are some feedback loops. I simplified my design as the following:
![image](https://user-images.githubusercontent.com/48234895/81821040-8606c100-9585-11ea-81cb-77f3c1bb7b3d.png)
In the image above, a plant reactor passes messages to a controller reactor, and the controller reactor gives feedbacks to the plant reactor.

When I tried to implement it using LF, it keeps telling me that reactions form a cycle, where every reaction depends on another reaction.

I tried to break the cycle by adding delays (use 'after' keyword, or use delayed reaction to set the output port). However, it still doesn't work... Please find the demo code in the attachment.

I am wondering if loops are not allowed in LF? Maybe I understand it in a wrong way.
Could you please give some advices on how to solve it? Thank you very much.

Best regards.

[Reaction_Cycle_Test.zip](https://github.com/icyphy/lingua-franca/files/4622367/Reaction_Cycle_Test.zip)

**Comment by edwardalee** [comment]
Thanks for posting this. There is bug with "after" that we are working on.  Your first example, however, can be made to work now. The cycle disappears if you reverse the order of declaration of the two reactions in reactor B. That is, reactor B should produce an output before reading the input. We have been struggling with how to suggest this fix to users automatically but haven't found a clean way yet.

**Comment by lhy673542630** [comment]
Yep! Thank you very much.

Best regards.

**Comment by edwardalee** [comment]
The bug with “after” has been fixed.  You should pull the latest updates.  Note that the API for the schedule() function has changed a bit also.  See https://github.com/icyphy/lingua-franca/wiki/Writing-Reactors-in-C#scheduling-delayed-reactions.

**Comment by lhy673542630** [comment]
Thank you so much for noticing me!

Best regards.
