### ISSUE TITLE
CLI arguments to C-targeted LF programs can trigger segfault

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#162]
```
[marten@yoga C]$ bin/MovingAverage -logging DEBUG
Error: Unrecognized command-line argument: -logging

Command-line arguments: 

  -f, --fast [true | false]
   Whether to wait for physical time to match logical time.

  -o, --timeout <duration> <units>
   Stop after the specified amount of logical time, where units are one of
   nsec, usec, msec, sec, minute, hour, day, week, or the plurals of those.

  -k, --keepalive
   Whether continue execution even when there are no events to process.

  -t, --threads <n>
   Executed in <n> threads if possible (optional feature).

Command given:
bin/MovingAverage -logging DEBUG 

Segmentation fault (core dumped)
```

**Comment by lhstrh** [comment]
Update: I got confused because I was running both TS and C tests. This is a C issue.

**Comment by lhstrh** [comment]
31f9087ea76f0c691315aed118dca3e05f04d55b

**Comment by edwardalee** [comment]
I have pushed a change that fixes the segfault, but I don't know how to support logging without taking a performance hit or recompiling to turn on logging (in which case, a command-line option won't work unless the generated program recompiles and replaces itself, which I suppose is not impossible).

**Comment by lhstrh** [comment]
My earlier comment was misdirected because I initially thought I was looking at a problem with the generated TypeScript code. I think it's fair to only support a logging directive at compile time for C...
