### ISSUE TITLE
`ReadOutputOfContainedReactor` test

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#163]
The C output is as follows:
```
[marten@yoga C]$ bin/ReadOutputOfContainedReactor 
---- Start execution at time Mon May 18 13:25:55 2020
---- plus 809466788 nanoseconds.
Startup reaction reading output of contained reactor: 0.
Reading output of contained reactor: 42.
Alternate triggering reading output of contained reactor: 42.
Test passes.
---- Elapsed logical time (in nsec): 0
---- Elapsed physical time (in nsec): 210,113
```

The first reaction is triggered by `startup` and reads `c.out`. This means that this reaction depends on the first reaction of `Contained`, so shouldn't it see `42` as well?

**Comment by lhstrh** [comment]
Both Cpp and TS report `42`. Aside from fixing this bug, we should change the test so that it checks the obtained values as well.

**Comment by edwardalee** [comment]
Interesting. The reaction of Contained and the startup reaction of the container are both assigned index = 0, which is incorrect, since the second has a dependency on the first. It is probably a coincidence that they get executed in the right order in Cpp and TS, since this index (level) allows either order.

**Comment by lhstrh** [comment]
I can't speak for Cpp, but it's not a coincidence in TS. This is the dependency graph that drives the execution:
![depGraph](https://user-images.githubusercontent.com/19938940/82277813-a8119200-993d-11ea-8425-c37a3c8442e7.png)
M[0] denotes the zeroth mutation, which is the one that is triggered by `startup`. My guess is that a dependency is missing in the graph that CGenerator uses...

**Comment by cmnrd** [comment]
A similar graph is used in C++:
![graph](https://user-images.githubusercontent.com/6460123/82290571-8b11a900-99a7-11ea-8e2f-54ebf069d0a4.png)
It is a bit simpler than for TS, because the C++ framework does not have the startup and shutdown mutations. Note that the analysis is done within the C++ framework when the application starts up. Therefore, it does not suffer from any bugs that may exist in the compiler analysis.

**Comment by edwardalee** [comment]
Why is this analysis being done independently by each target?  How did you generate this graph?  Can we move this analysis into GeneratorBase so bug fixes apply to all targets?

**Comment by cmnrd** [comment]
I designed [reactor-cpp](https://github.com/tud-ccc/reactor-cpp) to be usable independent of Lingua Franca. This allows writing reactor programs using plain C++. In consequence, the runtime needs to be able to build and analyze the dependency graph as there is no higher order entity it can be derived from. This is also a requirement for supporting mutations. When dependencies change, the graphs might need to be re-build and analyzed again during the execution.

reactor-cpp dumps the graph as a dot file which can be viewed for instance using xdot provided by the Graphviz package. Currently, the runtime simply dumps the file to `/tmp/graph.dot`. I plan to add a `--graph` command line option that optionally writes the graph to a given file.

**Comment by lhstrh** [comment]
The same answer holds for TS. A more fundamental reason for this design decision is not merely the ability to use of the framework _sans LF_ (which is important in its own right), but the fact that we leverage the language's object orientation features and therefore don't expand the entire instantiation hierarchy at compile time, like we do with C. In other words, we don't even have access to the graph at compile time in `TSGenerator` and `CppGenerator`. I'll fix the problem in `CGenerator`.

@cmnrd: I like the `--graph` switch you have. We're currently just printing the dot representation in our debug logging output; writing it to file is a better because you can more readily pipe it into rending tools.

**Comment by edwardalee** [comment]
There was a bug in the construction of dependencies in ReactionInstance. I have pushed a fix and also adjusted the test to check returned values.
