### ISSUE TITLE
Port lingers in diagram after having been deleted from the reactor definition

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#164]
The diagram synthesis still shows an output port after I removed it from the reactor.

**Comment by a-sr** [comment]
It seems to be [fixed](https://github.com/kieler/KLighD/commit/a32ce9dcc2b2fbc902d61e3d4a2215abcab5353d) in the latest maintenance release [1.1.1.](https://github.com/kieler/KLighD/releases/tag/release-2020-06-1.1.1) of KLighD.
At least, I could not reproduce the problem with 1.1.1 installed.

You will receive the maintenance automatically as an update if you have configured the correct updatesite (https://kieler.github.io/KLighD/). If the issue still occurs, please reopen this ticket.
