### ISSUE TITLE
Code generation for programs with multiple afters is broken

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#165]
This appears to be an issue with the AST transformation, as both C and C++ are affected. I added tests for both targets illustrating the issue: https://github.com/icyphy/lingua-franca/blob/master/test/C/Pipeline.lf, https://github.com/icyphy/lingua-franca/blob/master/test/Cpp/Pipeline.lf

In case of the C++ code generator, it stops writing out connections after the first connection with an after. Also, only one delay reactor is created. I don't know what happens for C, as it is difficult to parse the generated code.

I did not look into it yet, but possibly the AST transformation fails in creating multiple instances of the delay reactor.

**Comment by lhstrh** [comment]
Thanks the report! I'll look into this.
