### ISSUE TITLE
Set PATH in ProcessBuilder so as to not rely on Bash for executing target compiler

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#174]
[See comment on line 709 of GeneratorBase](https://github.com/icyphy/lingua-franca/blob/d62513754fadae1a7ba9a611abb570d72487c74d/xtext/org.icyphy.linguafranca/src/org/icyphy/generator/GeneratorBase.xtend#L709-717)

**Comment by Soroosh129** [comment]
The current situation is that the PATH used in ProcessBuilder to execute the command is the one Eclipse provides not the one in ProcessBuilder.environment(). Unfortunately at this time, there is no easy way of modifying this PATH variable in code. I am still looking for an elegant solution and very open to suggestions!

**Comment by lhstrh** [comment]
Thanks for looking into this! I had wrongly understood the way `ProcessBuilder` worked and assumed that setting its environment variables would affect the lookup of the executed command (not just the environment in which the command executes). It seems the current solution of resorting to Bash is probably the best we can do for now. I'll update my comment and close the issue...
