### ISSUE TITLE
Naming reactions

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#177]
This came up in earlier discussions already. In order to improve documentation and analysis of LF code, it would be very helpful if we could annotate reactions with names. This could be an optional feature and names could be easily omitted for simple reactors that maybe only have a single reaction. For more complex reactors, however, names provide a simple mechanism to refer to reactions in documentation, to improve readability of generated target code, or to get meaningful names in generated dependency graphs and trace files.

The most import question is: How can we do this syntactically?

I think that providing a name directly after the `reaction` keyword could be misleading:
```
reaction foo (bar) -> baz
```
This makes it easy to confuse reactions with function definitions. I think also that placing name, triggers, dependencies and antidependencies all together is difficult to parse when reading the code.

Alternatively, we could introduce an annotation syntax. For example:
```
@name foo
reaction (bar) -> baz
```
I think this would only make sense if we also see use for such annotations elsewhere in LF code.

Another option could be to use comments in combination with a certain convention on style. For instance:
```
/**
 * Does something very smart.
 *
 * Detailed description of all the smartness.
 *
 * @name foo
 */
reaction(bar) -> baz
```

Or we could provide the name by a comment after the reaction keyword:
```
reaction (bar) -> baz \* foo *\ {=
=}
```
or 
```
reaction (bar) -> baz {= // foo
=}
```

What do you think? Any other ideas?

**Comment by lhstrh** [comment]
This has also briefly come up during our meeting about diagram synthesis earlier today. 

Currently, comments can me made to appear in the diagrams by enabling a feature that finds associated comments and splices them into the diagram, but the comments are usually too long to be meaningful in the diagram. We figured that a "JavaDoc-like" directive such as `@label` could be used to narrow down the scope of what is shown in the diagram. So this would like like:

```
/**
 * Synopsis.
 *
 * Details.
 *
 * @label Something to appear in diagram.
 */
reaction(bar) -> baz
```

If we choose this style, would you still think we need a separate directive for names, or would it suffice to have `@label`?

**Comment by cmnrd** [comment]
I made a similar proposal above, only using `@name` instead of `@label`.

I think it would be good to have a mechanism that works without the need to write a comment block. Maybe we find other uses for an annotation syntax later on and can add this feature then. For now, I think the comment block based solution is completely sufficient.

**Comment by edwardalee** [comment]
I, on the other hand, feel that anything that encourages users to create a comment block is a positive thing. :-)

**Comment by lhstrh** [comment]
I don't have a strong preference either way. The only issue I can think of is that within comments we could potentially clash with `@` directives used by our code documentation generation tool of choice.

Note that because we support single-line comments we could also write `// @label` or `# @label`, so it's not necessary to declare an entire comment block...

**Comment by a-sr** [comment]
I just implemented diagram support for the `@label` annotation in comments (including single-line comments).
Here is a minimal example:
```
main reactor Main {
    // @label StepOne
    reaction() {==}
    /** 
     * Some text.
     * @label StepTwo
     */
    reaction() {==}
}
```
![labels](https://user-images.githubusercontent.com/25612037/86396148-b0315100-bca1-11ea-8e65-fe1dc6340ba5.png)

Is this sufficient?

**Comment by edwardalee** [comment]
Nice!!

**Comment by lhstrh** [comment]
Looks great!

@cmnrd does this resolve the issue?

**Comment by cmnrd** [comment]
If I understand [this commit](https://github.com/icyphy/lingua-franca/commit/a90aacafe928bedb2c1a92f9cbc28a0fcfde00c2) correctly, the label extraction only works from within the diagram synthesis. Would it be possible to move this code to ASTUtils so that it is available for the generators as well? Then the issue would be resolved for me.

**Comment by a-sr** [comment]
Yes, labeling reactions (or any other element in an LF program) is currently only a visual feature of the diagram.
Sure we can move that code to a more general place and reuse it in the generators.

You mentioned that you want to refer to reactions by their label in traces and the generated code, however, I am not sure if that is always feasible/sensible if the label is an unconstrained Unicode string but I guess that is the user's problem if a label is not meaningful.

![happy-labels](https://user-images.githubusercontent.com/25612037/86454370-6be49600-bd1f-11ea-81e3-e26815856e74.png)
