### ISSUE TITLE
Double underscore is reserved in C and C++

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#186]
Currently, the `__` (double underscore) prefix is used in the C target for variables that should not be accessed directly from reaction code. I am currently thinking about how I can better support the scoping rules in generated C++ code and will use a similar prefix mechanism. However, any identifiers starting with `__` are reserved in C++. While double checking and reading more about this, I found that this in fact also applies to C: https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

This means that the generated C code is not compliant to the requirements if libc. libc (and also the C++ std lib) use the same idea and prefix internal identifiers that are not intended to be exposed on the API interface with the double underscore. This, however, means that our generated C code could accidentally overwrite any of those internal identifiers and bad things may happen.

**Comment by cmnrd** [comment]
Here is another reference for both C and C++: https://en.cppreference.com/w/c/language/identifier

**Comment by edwardalee** [comment]
How about if we use prefix _lf_?

**Comment by edwardalee** [comment]
That should be `_lf_` (not italics).

**Comment by cmnrd** [comment]
Sounds good to me. This is what I am going for now in C++.
