### ISSUE TITLE
Strip out line directives from generated C code

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#187]
Line directives are used in generated C code to get enhanced error reporting, but they make the code somewhat difficult to read. @Soroosh129 suggested to strip them out after invoking the target compiler. Having this mechanism in place would also make it more appealing for use in generated C++ code.

**Comment by Soroosh129** [comment]
a013597e5fc4c9aaf854770d62c3261afb2dddb6 and 34eec4c8eb9b60f0b9b9525432592ece47c9d1d6 might fix this issue.

**Comment by lhstrh** [comment]
The fix is currently part of the `CGenerator`. If we'd want to use this for the C++ generator as well we'll probably want to factor it out, but we I think we can leave this up to @cmnrd.

**Comment by Soroosh129** [comment]
Just as a note, any target language can override the `getReadableCode()` in the `GeneratorBase` class.
