### ISSUE TITLE
Persistent input values

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#192]
The language specification does not seem to specify what happens when you read an input that is not present. In the C target, this results in reading the most recently received value (i.e., input values are *persistent*, lasting beyond the logical time at which they are present). The value is undefined (but probably zero) if no event has occurred on that input.  The following is a test case demonstrating this persistence.  What is the behavior in Cpp and TS?  Should we document persistent inputs as a language feature and add the following to the regression tests?
```
reactor Sampler {
    input in:int;
    input trigger:bool;
    output out:int;
    reaction(trigger) in -> out {=
        SET(out, in->value);
    =}
}
main reactor SamplerTest {
    timer t1(0, 200 msec);
    timer t2(100 msec, 200 msec);
    state count:int(0);
    s = new Sampler();
    reaction(t1) -> s.in {=
        SET(s.in, self->count++);
    =}
    reaction(t2) -> s.trigger {=
        SET(s.trigger, true);
    =}
    reaction(s.out) {=
        printf("Sampler outputs %d at time %lld.\n",
            s.out->value,
            get_elapsed_logical_time()
        );
    =}
}
```
The result of running this is:
```
---- Start execution at time Sun Jul  5 07:31:21 2020
---- plus 345032000 nanoseconds.
Sampler outputs 0 at time 100000000.
Sampler outputs 1 at time 300000000.
Sampler outputs 2 at time 500000000.
Sampler outputs 3 at time 700000000.
Sampler outputs 4 at time 900000000.
---- Elapsed logical time (in nsec): 1,000,000,000
---- Elapsed physical time (in nsec): 669,000
```

**Comment by lhstrh** [comment]
In TS, the value `undefined` is returned, which is interpreted as "absent." Note that in TS, `null` and `undefined` are distinct values, so when `set` is called on a port with the value `null`, the value would be `null` and the `isPresent()` would return `true`. It is not possible to use the value `undefined` as a parameter to `set`.

There sure is a use case for persistent ports (we've discussed them in the past), but it doesn't make any sense to me to be able to read a value when it is marked as absent. I think that we can introduce persistent ports as a feature, but I don't think they should be the default, and they would behave differently from regular ports in the sense that their values (and presence) would persist beyond the time at which they are set (i.e., they simply don't get reset at the end of a reaction cycle).

**Comment by cmnrd** [comment]
In C++, all values are represented by (smart) pointers. An absent value is given by `nullptr`. The `is_present()` method simply checks for inequality with `nullptr`. Unlike in TS, there is no distinction between `nullptr` and 'undefined'. If a reaction sets `nullptr` on a port, any sensitive reactions will be triggered but the value will be reported as absent. I am unsure if this is a reasonable behavior. It is probably better to not trigger any reactions if a port was set to `nullptr`. This was also discussed here: #119

**Comment by edwardalee** [comment]
What do you suggest the C target do if a port value is read when it is absent?  For primitive types, the value field of the port struct is the actual value, not a pointer. We could provide a GET() macro to access the port, but what should that do if is_present is false?  Exit?

I guess my only concrete proposal is that we declare the behavior to be "undefined."

**Comment by lhstrh** [comment]
I think the only reasonable specification of the described behavior would indeed be "undefined." 

This effectively leaves room for C to return the last value and TS to return `undefined`.

**Comment by lhstrh** [comment]
Based on our discussion today, we all agree the behavior should remain "undefined."

Moreover, @cmnrd pointed out that reading the last value for a port that is current absent should not be advertised as a feature of the C target, because it would interfere with our reference counting scheme that assumes that allocated memory can be freed at the end of a time step. It would be safer if the C runtime were to use an assertion and error out if a value was read from a port marked as absent.

**Comment by lhstrh** [comment]
Since we're more interested in performance than safety with the C target, we've decided that runtime detecting of reading stale values is too expensive. That said, there is a potential for statically detecting reads that are not guarded by an appropriate check, but having this is not a priority now.
