### ISSUE TITLE
Diagram view shows the AST

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#228]
I didn't use the LF IDE in a while. When I opened it today, I realized that the diagram view does not show the hierarchy of reactors anymore, but visualizes the AST.

![Screenshot_20201029_105738](https://user-images.githubusercontent.com/6460123/97553662-04410d80-19d6-11eb-9ed6-79dfee8cd8bb.png)

Is this a new feature? How can I switch back to the old view?

**Comment by lhstrh** [comment]
You can switch by clicking here:
![Screenshot from 2020-10-29 11-24-28](https://user-images.githubusercontent.com/19938940/97616372-b201eb80-19d9-11eb-9374-f47d0651498c.png)
and then selecting Syntheses->LinguaFrancaSynthesis. If only EObjectFallbackSynthesis shows, the you probably have a build error in the diagram package. In that case, you probably have to update the KIELER dependencies. You can do that by going to Help->Check For Updates in your development Eclipse (not the LF IDE).

**Comment by cmnrd** [comment]
Oh, right. I missed the build error in the diagram package. Updating KIELER fixed it. Thanks!
