### ISSUE TITLE
Representing microstep tardiness.

### ISSUE THREAD

**Issue by Soroosh129** [icyphy/lingua-franca#234]
In federated execution, a tardy handler could be used as an alternative body to a reaction that is receiving messages on the network via a logical connection.

For example, imagine the following simplified federated program:

```
reactor Sender {
    output out:int;
    ...
    // Send messages on out every microstep
    ...
}
reactor Receiver {
    input in1:int;
    input in2:int;
    reaction(in1, in2) {=
        // Body of the reaction
    =} tardy {=
        in1->tardiness // Indicates the tardiness on in1
        in2->tardiness // Indicates the tardiness on in2
    =}
}
federated reactor Main {
    sender1 = new Sender();
    sender2 = new Sender();
    receiver = new Receiver();

    sender1.out -> receiver.in1;
    sender2.out -> receiver.in2;
}
```

Currently, `in1->tardiness` is a scalar value of type `interval_t`, which is the `intended_time - current_time` (note the usage of time not tag). If a microstep tardiness occurs, the `tardy` handler will still be invoked but the value of `in1->tardiness` will be `0`. The issue is, in the above example, if `in1` is tardy but `in2` isn't, there is no way to tell in the `tardy` handler.

We do have a `tag_t` ( `.time, .microstep`) type that can be used for `tardiness`. However, `tag_t` is an instant in time and not an interval. How about `tag_interval_t`?

**Comment by lhstrh** [comment]
Using a `tag_interval_t` could work, but thinking about tags in terms of intervals doesn't strike me as all that intuitive.

Why not just store the original tag? We can provide a utility function `bool is_tardy(tag_t tag)` that returns true if the given tag is greater than the current tag, false otherwise. If the difference between the tag and the current tag is needed, this can also be easily computed. For this, too, we could provide a utility.

**Comment by Soroosh129** [comment]
Your suggestion could also work but to me the interval will be more useful in general use cases compared to the original tag, especially if the `time` field of the original tag isn't elapsed logical time.

**Comment by cmnrd** [comment]
To me it seems also more intuitive to use the original tag. If the difference between current tag and original tag is really needed, the programmer can still calculate the difference. We could also provide utility functions that calculate the difference in logical time and microsteps. You should also be aware that a `tag_interval_t` can have weird values. Consider an original tag `(1000, 4)` and the current tag`(1200, 1)`. Then the interval would be `(200, -3)`.

Could you elaborate why you think the interval is useful? I cannot think of a use case where this information it is needed. Maybe to reconstruct the original order? I would be happy to see an example.

**Comment by Soroosh129** [comment]
To me, the tardiness is useful because it can be used to adjust the STP offset dynamically. In your example, the tardiness currently calculated will be `(200, 0)`, which can directly be used to adjust the STP offset. Moreover, a microstep tardiness would indicate that possibly the rest of the messages intended for the current logical time coming from a particular federate will be tardy, and possibly can be skipped altogether.

I want to point out that I think the tardiness for network messages should either be in logical time or in microstep. So either `(x, 0)` or `(0, x)` although this is a separate debate. I don't think it makes sense to have a tardiness `(200, 1)`.

In case we decided to go with storing the original tag, what do you suggest we call it? `port->original_tag`?

**Comment by edwardalee** [comment]
I suggest we replace tardiness:tag_interval_t with intended_tag:tag_t.

**Comment by Soroosh129** [comment]
Okay. I think that the consensus is to store the original `intended_tag`.
