### ISSUE TITLE
In lingua-franca/compiler, why does "make setup" use the svn version of accessors?

### ISSUE THREAD

**Issue by cxbrooks** [icyphy/lingua-franca#24]
In lingua-franca/compiler, running "make setup" downloads accessors using svn and repo.eecs.  Instead, shouldn't git and https://github.com/icyphy/accessors be used?

If the repos are the same, then maybe a comment should be displayed that says this?

```
bash-3.2$ make setup
svn co https://repo.eecs.berkeley.edu/svn-anon/projects/terraswarm/accessors/trunk/accessors
A    accessors/web
A    accessors/web/net
```

**Comment by lhstrh** [comment]
Obsolete because `/compiler` was removed.

**Comment by schoeberl** [comment]
thanks for closing this, it was on my TODO list to look into it and close.

Cheers,
Martin
