### ISSUE TITLE
Kieler Diagram not working 

### ISSUE THREAD

**Issue by zombieunipineapples** [icyphy/lingua-franca#240]
http://prntscr.com/vo0dzg
This occurred on both a windows 10 system and Linux virtual machine running on 64-bit ubuntu.

**Comment by lhstrh** [comment]
Have you installed/updated the Kieler dependencies? Also see [this wiki entry](https://github.com/icyphy/lingua-franca/wiki/Diagrams#enabling-diagram-synthesis). If you had diagrams working correctly in the past, then you may have to update KLightD. I believe there were some recent changes in their API that weren't backward compatible. In Eclipse, go to `Help`->`Check for updates`.

**Comment by lhstrh** [comment]
@zombieunipineapples have you been able to resolve the issue?

**Comment by lhstrh** [comment]
In Eclipse, go to `Help > Check For Updates` and install the available KLighD updates. Then rebuild the `org.icyphy.linguafranca.diagram` project and launch the LF IDE again.
