### ISSUE TITLE
Syntax for pipelines

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#247]
It would be nice to have a compact syntax for pipelines. Maybe something like this:

```
pipeline = new[width] Stage with out1 -> in1, out2 -> in2 after delay;     // Connect stages.
source.out -> pipeline.in1;     // Connect to the first stage input
pipeline.out2 -> sink.inp;      // Connect to the last stage output
```

**Comment by Soroosh129** [comment]
By `width` do you mean the depth of the pipeline? How would a bank of pipelines work?

**Comment by lhstrh** [comment]
Yes, `length` would have been a more appropriate name for the variable. If we want to combine those, we'll probably want to use a distinct syntax for pipelines.

Perhaps:
```
pipeline = new Stage (out1 -> in1, out2 -> in2)[length];
bank_of_pipelines = new[width] Stage (out1 -> in1, out2 -> in2)[length];
```
IDK...

**Comment by cmnrd** [comment]
This is supported now and an example can be found here: https://github.com/icyphy/lingua-franca/blob/master/example/C/src/Patterns/Chain_02_Pipeline.lf
