### ISSUE TITLE
How to trigger the reaction of an extended (i.e. super) reactor from a sub reactor?

### ISSUE THREAD

**Issue by stustd** [icyphy/lingua-franca#251]
Reactors communicate through inputs and outputs.
Inherited behavior (through extending reactors) shares their reactor states (i.e the reactor state can be hierarchically developed).
But how can the reaction of a super reactor be triggered by one of its sub reactors?
The problem I have is that say "logical action act;" is only visible in the reactor with corresponding reaction -- from there it can not be used (i.e. scheduled) in any of its sub reactors. How would I trigger that reaction further down in the inheritance/extension hierarchy? Thanks.

**Comment by edwardalee** [comment]
I have pushed a fix so that actions in a base class are visible in the subclass. I pushed a test in tests/C/InheritanceAction.lf. Is this what you had in mind?

Note that inheritance is not fully developed yet and is not documented.

**Comment by stustd** [comment]
Yes indeed, that's what I meant; thanks!

I understand that inheritance is not fully developed yet and is not documented. I hope you don't mind me starting using it already and communicating my findings with you...

**Comment by edwardalee** [comment]
We don’t mind at all!  Just as long as you realize you will counter problems...
