### ISSUE TITLE
Add clock synchronization info to tracing

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#254]
- [x] Log updates that are being made to the offset
- [x] Each federate generates its own trace file
- [x] Get a sense of how much drift there is

**Comment by edwardalee** [comment]
These three are all done. On my machines, I'm not seeing any significant drift.  The clock synchronization algorithm concludes that the clocks on my machines differ by about 7 msec.  However, the sounds are about 50 msec apart. If I turn off clock synchronization, this increases to about 100 msec.
