### ISSUE TITLE
Add sound support for Linux

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#262]
Currently, there is only sounds support for the MacOS platform. The most straightforward path seems to be ALSA.

**Comment by Soroosh129** [comment]
I have pushed four variants of Rhythm for Linux to the `clock-synchronization` branch (all credit goes to @edwardalee for creating the Mac variants of these that are essentially untouched when ported to Linux):
```
RhythmLinux.lf   # Most straightforward demonstration of using ALSA on Linux
RhythmLinuxDistributed.lf  # A fully fleshed-out distributed Rhythm application with a Master and a player with one-way communications
RhythmMacDistributedIndependent.lf  # Essentially two RhythmLinux federates with no communication
RhythmMacDistributedNoUI.lf  # Same as RhythmMacDistributedIndependent but without a UI. This variant only plays the claves instrument. This example is convenient because it can be launched directly using our federated launch scripts. 
```

**Comment by lhstrh** [comment]
That is great news! It seems like a lot of useful commits have slipped into the `clock-synchronization` branch that are not particularly related to clock synchronization... Is the plan to cherry pick or should we just merge `clock-synchronization` into `master`?

**Comment by Soroosh129** [comment]
I think the clock synchronization algorithm itself appears to work reasonably well. I for one think that we might be better off merging the entire branch into `master`. We can even decide on whether to leave it off by default or not (my vote is that it should be on).

**Comment by lhstrh** [comment]
OK, why don't you submit a PR then? That will also give us some time to look at the changes ahead of our next code review meeting.

**Comment by edwardalee** [comment]
One change I suggest before we do a PR.  I suggest we remove, for now, the "regression" option in the target properties. Also, I suggest that the default behavior be to perform clock synchronization at startup only, not during execution.  The possible properties could be therefore: off, startup, on, where startup is the default.  When we have "regression" implemented, we should probably just assess whether this is better and use it by default. We could also add more options, where "on" is interpreted as "I don't care which method you use."

**Comment by lhstrh** [comment]
This functionality has now been merged into master.
