### ISSUE TITLE
Segfault in C++ BankToBankMultiportAfter.lf

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#269]
There appears to be a bug in the C++ runtime (See https://github.com/icyphy/lingua-franca/runs/1744224571?check_suite_focus=true). This one might be hard to reproduce, but we should try to find the cause.

**Comment by lhstrh** [comment]
Bumping this because the problem resurfaced. See: https://github.com/icyphy/lingua-franca/runs/1825380807?check_suite_focus=true

**Comment by cmnrd** [comment]
Another issue appeared in DoubleReaction.lf https://github.com/icyphy/lingua-franca/runs/2107914544?check_suite_focus=true 

This might be related or a complete different issue, but needs investigation nonetheless.

**Comment by cmnrd** [comment]
I think I found a fix to the problem, but I am still not 100% sure why the segfaults and other issues appeared. `reactor-cpp` is a bit more conservative now in acquiring locks, which appears to fix the issue. I am not happy with this solution because I don't really know what went wrong in the first place, but for now I will close this issue, and I will keep analyzing and improving the reactor-cpp runtime in hope to find the root of this problem.
