### ISSUE TITLE
Nondeterministic failure in federated test

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#274]
See `DistributedLoopedPhysicalAction` in https://github.com/icyphy/lingua-franca/runs/1825970410?check_suite_focus=true

**Comment by Soroosh129** [comment]
Added more slack in cb7365aa4ec295509d8f09cc131d6bc1d8a45e0c, which appears to have resolved the issue. Generally after moving from Travis to GitHub actions, we discovered that tests that rely on physical time should have a lot more slack to pass (for future reference).
