### ISSUE TITLE
DistributedLoopedPhysicalAction fails due to logical time moving past events in the event queue

### ISSUE THREAD

**Issue by Soroosh129** [icyphy/lingua-franca#279]
It seems that with the recent changes, `test/C/DistributedLoopedPhysicalAction.lf` now consistently fails on MacOS because of the following problem:
```
Federate 1: ERROR: __next(): Popped an event that has a relative intended time (678988000) that is earlier than the current relative time (679000000).
```
The specific time values I believe bear no significance on the issue. This test uses centralized coordination. Maybe this is related to the incomplete implementation related to physical actions?

**Comment by edwardalee** [comment]
I believe this is fixed in the coordinated branch.

**Comment by lhstrh** [comment]
OK, will close when merged.
