### ISSUE TITLE
Tests and output behavior

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#286]
This tickets is a meant to track progress in the implementation effort toward a Gradle/JUnit based test framework for LF.

~~- [ ] Add the `test` modifier to the grammar.~~
- [x] Make the regular main reactor name optional. If a name is provided, it must match the name of the file.
- [x] Let the source output location be parameterized by the source input path.
- [x] Add a check to the validator to ensure that there exist no other main reactors in the package that have the same name.
~~- [ ] Add a check to the validator to ensure that test reactors are named.~~
- [x] For tests, produce executable artifacts in a separate directory that follows the package structure to avoid collisions between equally named tests in different files. 
- [x] Change the new test harness to look for `.lf` files also in the `example` directory

**Comment by edwardalee** [comment]
I thought we had decided that we didn't need more than one test reactor and that it didn't need a name. ???  The reasoning was that subtests could be created within that reactor.

Also, I thought we decided that the main reactor should have the same name as the file if it has a name.

**Comment by lhstrh** [comment]
That's not what I recall, but let me explain the reasoning. Assume we have two packages: `foo` and `foo.bar`, each of which has a `Baz.lf`. If we flatten the hierarchy in the `bin` directory `foo.Baz` and `foo.bar.Baz` both map to `bin/Baz`. Hence, as @cmnrd pointed out, allowing to rename the main reactor provides a means to resolve such conflict. We don't have this problem with tests, on the other hand, because we will replicate the package hierarchy in the output directory.

I don't see why it would be useful to limit the number of tests per file to one. It wouldn't be hard to allow more, and it promotes modularity (versus being forced to put everything in one big test where all tests code gets instantiated). Each test could be documented properly, and if a test fails, it will be clearer where the problem is. It would also be nice to have closely related tests in the same file rather than scattered over multiple `.lf` files, I think.

**Comment by edwardalee** [comment]
The reasoning to the contrary is as follows: A “project” is a coherent collection of code around one goal.  It would be confusing in such a scenario to provide two executable programs with the same name.  Renaming the executable inside the file makes it even more difficult to connect the executable in bin with the source file.  You have to search the _contents_ of all .lf files everywhere in your tree.  It’s bad enough that running ‘lfc Baz.lf’ puts the result somewhere like ../../../bin.  Now giving it name like Xyz does not seem like a good idea to me.

I feel less strongly about whether having multiple tests in a .lf file, but a similar argument applies.
If I see a file bin/test/x/y/z/Xyz that is failing, how do know that it is src/x/y/z/Baz.lf that needs to be fixed?

**Comment by cmnrd** [comment]
> I feel less strongly about whether having multiple tests in a .lf file, but a similar argument applies.
If I see a file bin/test/x/y/z/Xyz that is failing, how do know that it is src/x/y/z/Baz.lf that needs to be fixed?

The test would probably be generated as `test/x/y/z/Baz/Zyz`, making it unambiguous where the test originates from and avoiding any name conflicts between tests in neighboring .lf files. After all the test reactor `XyZ` would have the FQN `x.y.z.Baz.Xyz`

I must admit that I am still confused by the `test` keyword. Do we plan to use this for our LF compiler tests or as a mechanism for unit-tests in LF programs/libraries?

> I feel less strongly about whether having multiple tests in a .lf file, but a similar argument applies.
> If I see a file bin/test/x/y/z/Xyz that is failing, how do know that it is src/x/y/z/Baz.lf that needs to be fixed?

I could ask the same question about a C project, where running `make` produces a binary `foo` from multiple source files. How do you know which file to check if the binary does not work? I don't think we can (or should) answer that question in our language/compiler design. This is a matter of organizing the project in a clean manner, but how to do this is completely up to the project maintainers.

I don't have a strong opinion about naming binaries, but I am leaning towards naming binaries the same as the input .lf file. The default should be that main reactors are unnamed, if needed for better readability of papers we can optionally name the main reactor, but then it needs to be identical to the file name. I think this was the last version we discussed in our meeting, but I am not sure since we went back and forth on this.

**Comment by lhstrh** [comment]
Comments below...

On Fri, Mar 5, 2021 at 7:06 AM Edward A. Lee <notifications@github.com>
wrote:

> The reasoning to the contrary is as follows: A “project” is a coherent
> collection of code around one goal. It would be confusing in such a
> scenario to provide two executable programs with the same name. Renaming
> the executable inside the file makes it even more difficult to connect the
> executable in bin with the source file. You have to search the *contents*
> of all .lf files everywhere in your tree. It’s bad enough that running ‘lfc
> Baz.lf’ puts the result somewhere like ../../../bin. Now giving it name
> like Xyz does not seem like a good idea to me.
>
> I see your point. I agree that there are typically few main reactors in a
single project, so the likelihood of collisions seems low to start with. If
we require that the main reactor is named the same as the file, then we
have to check for conflicting main reactors in the project and warn if one
exists. The remedy would then be to rename the main reactor rather than
renaming the file. I'm OK with this.

> I feel less strongly about whether having multiple tests in a .lf file,
> but a similar argument applies.
> If I see a file bin/test/x/y/z/Xyz that is failing, how do know that it is
> src/x/y/z/Baz.lf that needs to be fixed?
>
> I would put the binary in bin/test/x/y/zXyz/Baz, so it wouldn't be
ambiguous as to which source the binary relates to.

**Comment by cmnrd** [comment]
> I see your point. I agree that there are typically few main reactors in a single project, so the likelihood of collisions seems low to start with. If we require that the main reactor is named the same as the file, then we have to check for conflicting main reactors in the project and warn if one exists. The remedy would then be to rename the file rather than renaming the main reactor. I'm OK with this. I updated the top post in this thread accordingly.

We could also provide an alternative way for resolving these conflicts in the future. I am seeing this problem more from the perspective of a standalone compiler. From this perspective, I think it only makes sense to name the resulting binary the same as the input file. However, it would also be reasonable to allow specification of an alternative name via CLI arguments. To make this simpler to use, a future package manager (or build tool) would look up the names from a configuration file and invoke `lfc` accordingly.

**Comment by lhstrh** [comment]
An update on this: after some deliberation we've decided to go back to the original approach of scanning directories named `test` and interpreting their contents as tests, without resorting to new syntax. The key reason that brought us to this decision is the fact that target properties no longer make much sense in the presence of multiple main reactors.  I'll update the title of this issue and update the list of action items accordingly.
