### ISSUE TITLE
Crossbar connections

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#288]
I am finding a common pattern is that I want to create a bank of reactors in which each has an output that is sent to all the other reactors in the bank.  I think we can repurpose existing syntax for this as follows:
```
reactor Foo (num_inputs:int(1)) {
    input in[num_inputs]:int;
    output out:int;
    reaction(startup) -> out {=
        SET(out, 42);
    =}
    reaction(in) {=
        ...
    =}
}
main reactor ThreadedThreaded(width:int(4)) {
	a = new[4] Foo(num_inputs = 3);
	(a.out)+ -> a.in;
}
```
The meaning of this is that the output of each instance of `Foo` is sent to the input of each of the *other* instances of `Foo`.  Alternatively, it could mean to send to *all* instances of `Foo`, including itself, but that seems sort of silly. And in the case of federated execution, we would probably have to treat the result self-loop specially.

Thoughts or comments?

**Comment by lhstrh** [comment]
In the original syntax the `+` operator is used to "repeat" the creation of connections until all ports on the right-hand side are assigned; the number of channels on the left-hand side must divide the number of channels on the right-hand side. What is the meaning in case `a.in` is a multiport (and `a.out` isn't)?

Perhaps it would be better to use another type of arrow that means "connect to all others in the bank" and refer to it as a "crossbar" connection or something like that. Candidates that come to mind are `=>` or `+>`. In that case, one would simply write `a.out => a.in` and perhaps even `(a.out)+ => a.in` in case the goal is to do a "rolling" distribution of channels from `a.out` to the input channels of the respective `a.in` ports.

**Comment by edwardalee** [comment]
This is handled already, and sending to oneself in federated execution works fine (it does not go over a socket).
