### ISSUE TITLE
Create hook for nightly builds in Github Actions

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#305]
Create a workflow that:
- [x] builds nightly (CRON job)
- [x] creates a `nightly-build` tag/release
- [x] publishes build artifacts as part of `nightly-build` release
- [x] Verify locally that the action works
- [ ] create and place a Github Token for the releases

**Comment by Feliix42** [comment]
I created a dedicated branch for implementing this, `ci/nightly-build`. The new workflow will create a nightly build every night at 12AM UTC via `mvn compile` and `mvn package`. The build is also triggered when a new release is drafted.

All that's missing now is a place to push the created build artefacts to. Maybe a statistical fact on the side: A build currently uses ~200MiB per operating system, which makes around 600MiB in total per nightly build.

**Comment by lhstrh** [comment]
Very cool!

It looks like we could use the tag/release feature from GitHub to store the build artifacts. The idea is simple: move the `nightly-build` tag to the current `HEAD` every night, and attach the created artifacts to the release. There are several GitHub projects that do this. Here's an example: https://github.com/Chatterino/chatterino2/actions/runs/947603138/workflow

It uses this action: https://github.com/pajlada/create-release/releases

It is a fork of the create-release [described here](https://trstringer.com/github-actions-create-release-upload-artifacts/) which is no longer maintained. Not sure if this is the fork we want; there might be others that are more suited. We could also use `curl` and use the GitHub API directly: https://docs.github.com/en/rest/reference/repos#releases

Not sure if we need to retain intermediate results between workflows, but there's some documentation on that, too: https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts

**Comment by Feliix42** [comment]
I have now added a release action that _should_ create/update the same release every night. For now it's without caching. Should we run into CI time limits, we could consider caching results. I used another fork/version of the [create release action](https://github.com/marketplace/actions/create-release), but it should work nonetheless.

What the action needs to work is a token for push access. Could you please [create an access token](https://github.com/settings/tokens/new) with the rights
- `repo:status`
- `repo_deployment` and 
- `public_repo`?

Place the token then as a secret with the name `GITHUB_TOKEN` (via `Settings -> Secrets`). In the meanwhile I'm running the workflow locally to check if the action will work. Once that succeeds and the secret is in place the PR should be ready to merge.

**Comment by lhstrh** [comment]
I've created an access token and added it to the organization's secrets, but the prefix `GITHUB` is not permitted. Instead of `GITHUB_TOKEN`, I called it `NIGHTLY_BUILD`.
