### ISSUE TITLE
Allowing keywords as identifiers

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#33]
Not convinced this is a good idea. The way the grammar is set up, we get away with parsing it, but it breaks syntax highlighting: in the statement `input input;` both occurrences of the keyword are highlighted. I think it looks bad... What's wrong with `input in` and `output out` and just disallowing the use of keywords as identifiers?

**Comment by edwardalee** [comment]
Ok with me.

Edward

---------
Edward A. Lee
EECS, UC Berkeley
eal@eecs.berkeley.edu
http://eecs.berkeley.edu/~eal

**Comment by lhstrh** [comment]
OK, made the change.
