### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#332]
We should customize our IDE:
- [x] Icon with LF logo
- [x] Splash screen
- [x] LF File type and "New File Wizard"
- [x] LF Project and "New Project Wizard"
- [x] Show text with pointers to documentation on (first?) launch

**Comment by lhstrh** [comment]
Also related to #352.

**Comment by a-sr** [comment]
I added [icons and a splash screen](https://github.com/icyphy/lingua-franca/commit/75905b6f8502ba0759c3678b98e86cb21fdfd23d) and also [a file icon and a file creation wizard](https://github.com/icyphy/lingua-franca/commit/94c19bf8766ddcca5aea3cf339d0f20b32c3a631)

I wasn't really creative, so every image is simply the icon (the one I found somewhere in the repo). It would be best if someone could take a look at it and maybe adjust the design, especially for the splash screen.
If you do so, make sure you save the image in 24-bit format (8R, 8G, 8B) ([source](https://wiki.eclipse.org/Platform-releng/Updating_Branding))

**Comment by a-sr** [comment]
All the images are located in org.lflang.product and org.lflang.ui (for the file icons).
If you want to adjust the product configuration, e.g. license and copyright etc., this is done in the [product definition file](https://github.com/icyphy/lingua-franca/blob/master/org.lflang.rca/lflang.product) (best open it in Eclipse to have a proper editor). However, this configuration is primarily used at compile time. There is another definition in the product plugin (providing branding at runtime) [org.lflang.product](https://github.com/icyphy/lingua-franca/tree/master/org.lflang.product).
In the first editor tab of the product definition file, there is a button to synchronize the product definition with the product plugin. It is important to do this if you change anything in the product definition.

**Comment by a-sr** [comment]
@Soroosh129 I moved the welcome page you added in May to the product plugin because I needed a different type of welcome page.

**Comment by cmnrd** [comment]
I noticed today that in the RCA the name "Epoch" does not seem to appear yet. The splash screen says "Starting up Lingua Franca". Also the title bar says "Linigua Franca" not Epoch.

**Comment by lhstrh** [comment]
See PR https://github.com/icyphy/lingua-franca/pull/464

**Comment by lhstrh** [comment]
It is true that a link to our wiki is displayed upon first start, but it doesn't look great:

![image](https://user-images.githubusercontent.com/19938940/130304386-5c04c5e9-cbc7-4417-85ce-779cd61004c7.png)

Of course, since we're dealing with Eclipse, the contents of the welcome message are not given in plain HTML, MD, or any other sane format, but some kind of custom XML. Is is possible to (rather than point to an external web page with a clickable link), just load an external web page? That would make our lives a lot easier...
