### ISSUE TITLE
Bug with detection of cyclic dependencies

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#342]
In the following model: lingua-franca/example/C/src/Patterns/Chain_02_Pipeline.lf

In theory, it should be possible to replace the main reactor with this, which is much more elegant:
```
main reactor {
    r0 = new SendCount(period = 100 msec);
    rp = new[4] TakeTime(approximate_time = 100 msec);
    r5 = new Receive();
    r0.out, rp.out -> rp.in, r5.in;
}
```
However, this triggers an error:
<img width="842" alt="Screen Shot 2021-05-20 at 1 05 15 PM" src="https://user-images.githubusercontent.com/8513334/119041897-08ca1500-b96c-11eb-85c8-3135ded24caf.png">

There is actually no cyclic dependency, but to know that requires doing the cycle analysis on ReactorInstance data structure.

**Another bug**:
In the model lingua-franca/example/C/src/Patterns/Loop_03_Dual.lf, if you follow the instructions in the comment to "Try replacing SendOnceAndReceive with ReceiveAndSendOnce to observe the formation of a causality loop," you will notice that the causality loop is not detected by the diagram but is detected by the code generator.  This too will hopefully be fixed once we use ReactorInstance as the master data structure.

**Comment by lhstrh** [comment]
FYI: The validator in the `reaction-graph` branch no longer reports this cycle.

**Comment by edwardalee** [comment]
This is fixed with the merge of the reaction-graph branch, commit a4b1342.
