### ISSUE TITLE
IDE complains about not finding `bash` in Windows

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#361]
Saw this on a clean Windows install on a machine that doesn't have the appropriate dev tools for the used target. Instead of complaining about `bash`, it should complain about the actually required dependencies that are missing.

**Comment by cmnrd** [comment]
The error message could also mention that the C++ target supports Windows without WSL and could be used as an alternative.

**Comment by lhstrh** [comment]
I think the problem is that we are poking around to find the executable using bash even though bash itself is not available. Maybe we should revisit this strategy. We could also use a configuration file to compensate for missing paths; less automated but also less error prone...

**Comment by soyerefsane** [comment]
Would an additional error message for WSL if you are on a windows machine with a C target be adequate? Or do you think we should change the way we compile for windows?

**Comment by cmnrd** [comment]
I think on the long term we should aim at supporting native Windows compilation for the C target. However, this is a larger endeavor. So for now a better error message should suffice. I think the compiler should detect that it is running on Windows and check if WSL is installed. If not, it can tell the user to either install WSL or to switch to the C++ target which supports Windows natively. I am not sure how to detect reliably if WSL is installed, but just checking if bash is available on Windows is likely sufficient.
