### ISSUE TITLE
The diagram view does not show deadlines anymore

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#378]
I am not sure where this broke. In older version of LF, the diagram view indicates deadlines. However, in the current master no deadlines are shown.

**Comment by edwardalee** [comment]
Fixed.  In the process, I discovered an error where deadline inference wasn't quite right. Specifically, even if an upstream reaction had a smaller deadline than a downstream one, the upstream one was inheriting the downstream one. I fixed that too. Apparently, we have no test for that condition.
