### ISSUE TITLE
New Oomph setup doesn't include nor find C/C++ extensions

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#385]
The new Oomph configuration does not include C/C++ editor support. Neither did the old one, but with the old configuration, when I tried to open a C/C++ file, Eclipse would offer to install the software.  It no longer does that.  Now I have to manually go to Help, Install New Software, and search through the vast number of matches to C/C++.

Is there any way our configuration could include C/C++ support?

**Comment by cmnrd** [comment]
Closed by #462
