### ISSUE TITLE
Target code lexer cannot parse Rust lifetime annotations

### ISSUE THREAD

**Issue by oowekyala** [icyphy/lingua-franca#407]
The lexer for target code blocks expects quotes to be paired:

https://github.com/icyphy/lingua-franca/blob/0fc05d4fb3e43c60554ef4803fa6df1b57a7c82d/org.lflang/src/org/lflang/LinguaFranca.xtext#L453-L455

because of the STRING terminal, but lifetime annotations in Rust are written `'a` or `'b`.

The following reactor fails to parse:
```rust
target Rust;
main reactor StructAsState {
    preamble {=
        struct Hello {
            name: &'static str,
            value: i32,
        }
    =}
}
```
with
> ERROR:mismatched character `'<EOF>'` expecting `'''` (file:/.../Source.lf line : 5 column : 20)

----
Possible fix: add an alternative for rust lifetimes (which is also the syntax of symbols in Scala so it could be useful). Or maybe, we could stop lexing target code, though I suppose there's a good reason this is done?

**Comment by lhstrh** [comment]
We're tokenizing the target code because otherwise the code gets rendered as a single text block in Epoch. It's not a very pretty solution, but it was the only way I found to be able to render target code somewhat decently in the IDE...

**Comment by lhstrh** [comment]
The problem is that, AFAIK, tokens are matched against terminals in the order they are defined, and `STRING` is defined in `org.eclipse.xtext.common.Terminals`, which is imported in our grammar. If we want to defined a terminal `LIFETIME: "'" ID` before `STRING`, we have to redefine the common terminals rather than import them. I tried adding them to a separate file `LFTerminals.xtext` and then import that instead, but that lead to a string of inexplicable Java errors about inconsistent hierarchies...

**Comment by cmnrd** [comment]
Oh, interesting. This is actually also a problem in C++ where `'` can be used as digit separator:
```
long long decn = 1'000'000'000ll;
```
I guess we also don't support the `ll` annotation in that example.

It's not beautiful, but maybe we need a special escape token. Of course we should make an effort to cover the target languages to the largest extent possible, but I don't think we would be able to always cover all the different corner cases. So maybe we should do something like this for now:
```
preamble {=
        struct Hello {
            name: {=&'static=} str,
            value: i32,
        }
    =}
```

**Comment by lhstrh** [comment]
Let me try to find a way around this and let me get back to you. I have some ideas...

**Comment by oowekyala** [comment]
Why not just lex words? (as in whitespace delimited groups of characters) Would this not be enough for Epoch to render them somewhat properly? I think the more we try to be language-specific, the more issues we'll hit.. . Eg the grammar for integer literals is slightly different in every language, as you show here, and supporting every corner case is impossible

**Comment by lhstrh** [comment]
As per our discussion on Wednesday, the proposal is to discontinue recognizing strings delimited by single quotes in LF. This also applies to the target properties. Of course, YAML _does_ allow single-quoted strings, but our target properties only allow a subset of YAML anyway.
