### ISSUE TITLE
Diagrams do not show connections from banks to the container ports

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#408]
The following LF program produces an incomplete diagram (see below):
```
target Cpp;

reactor Foo {
    input in:void;
    output out:void;
}

reactor Bar {
    output[4] out:void;
    
    foo = new[4] Foo();
    
    foo.out -> foo.in;
    foo.out -> out;
}

main reactor {
    bar = new Bar();
}
```
![test](https://user-images.githubusercontent.com/6460123/125413342-8aeed422-c45d-431c-ace8-89ed2b12a3b0.png)

The second connection from `foo.out` to Bar's output port `out` is not displayed. Apparently, this only happens if `foo` is a bank. When modifying the program so that `foo` is a single instance, the connection is correctly displayed.

**Comment by edwardalee** [comment]
Fixed with commit d1f718efbbb45ecce5313a0c0c020dc6b1956d96.  Another corner case I missed.  Added a C test.
