### ISSUE TITLE
NullPointerException in C generator and diagram synthesis if width's cannot be inferred by the compiler

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#409]
The following valid (according to the validator) LF program triggers a NullPointerException both in the diagram synthesis and in the C code generator.
```
target C;

reactor Foo {
    input in:void;
    output out:void;
}

reactor Bar(width:int(4)) {
    output out:void;
    
    foo = new[width] Foo();
    
    foo.out -> foo.in;
}

main reactor(a:int(4), b:int(2)) {
    bar = new Bar(width={=a/b=});
}
```
The problem lies in this line `bar = new Bar(width={=a/b=});`. I assume the reason for the exception is that the width cannot be inferred due to the target code computation. However, this should be detected by the validator and shown as a proper error message. 

In C++ with #387, this program is actually valid and works as expected. Thus, the diagram view should visualize the program, even if the width cannot be inferred.

**Comment by edwardalee** [comment]
Fixed diagram synthesis with commit 3ea3a1c493d44e0897138648571f94a20df1fb26. The C generator will still not be able to generate code for this as it cannot infer the width at code generation time. Now, the error message correctly reflects this, once other errors in the code are fixed:
```
target C;
reactor Foo {
    input in:int;
    output out:int;
}

reactor Bar(width:int(4)) {
    output out:int;
    
    foo = new[width] Foo();
    
    foo.out -> foo.in;
}

main reactor(a:int(4), b:int(2)) {
    bar = new Bar(width={=self->a/self->b=});
}
```
The error reported is `cannot infer width`.
