### ISSUE TITLE
Organization of benchmark directories

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#410]
The lingua-franca/benchmark directory is not well organized right now. The C and Python subdirectories have no `src` directory, and the Cpp subdirectory has `src` in the wrong place (IMO) and has unnecessary subdirectories for each benchmark.  Anyone mind if a rearrange these in the master branch?  I propose the following organization:
```
benchmark
|- C
    |- src
        |- Savina
           |- Philosophers.lf
           |- PingPong.lf
           |- etc.
        |- Distributed
           |- TimeLimitDistributed.lf
           |- etc.
```
and similarly for the other target languages.

**Comment by cmnrd** [comment]
While I think it's a very good idea to reorganize the benchmarks, I don't think it should happen on master. There are currently three open PRs touching things in the benchmark directory: #384, #401, #406. So moving things on master is likely to conflict with those PRs. Also, #384 already does some reorganization in the C directory. 

I think we should come up with a structure everyone agrees with, and do the actual restructuring more carefully in individual PRs. That said, I don't agree that the src directory is in the wrong place. I see the Savina benchmark suite as one independent project and the set of distributed benchmarks is a different project.

When it comes to reorganizing, we also need to make sure to correctly adjust the configuration files in `benchmark/runner/conf`. I think it would be a good idea to have a test pass for the benchmark runner that ensures that all the benchmarks are found and compile without actually running the benchmarks.

**Comment by edwardalee** [comment]
OK, I will hold off.  I see your point about the src directory in Cpp. It can certainly be within the Savina directory. What about the extra level of directories for each benchmark? Do those have a purpose?

**Comment by cmnrd** [comment]
Some benchmarks consist of multiple files, like [MatMul](https://github.com/icyphy/lingua-franca/tree/master/benchmark/Cpp/Savina/src/recmatmul) for instance. I guess for those, the subdirectory makes sense. I think Hannes tried to be consistent and just use the subdirectories for all the benchmarks, but we could think about removing them for the single file benchmarks. Maybe an alternative could be to move all `*.lf` files to the top directory and have additional directories with the same base name if additional files are required. So in case of the MatMul benchmark, we could have a structure like this:
```
benchmark
|- Cpp
    |- Savina
        |- src
           |- MatMul.lf
           |- MatMul
              |- MatMul.cmake
              |- MatMulCommon.hh
              |- MatMulCommon.cc
           |- PingPong.lf
           |- ...

``` 

The Savina benchmark suite divides the benchmarks in three categories: micro, concurrency and parallelism. We might also want to reflect those categories in the directory structure.

**Comment by lhstrh** [comment]
What @cmnrd proposes looks reasonable to me. It also makes sense to me to organize them by category...

**Comment by cmnrd** [comment]
As discussed in our weekly meeting today, the structure should look like this (per example of the C++ target):
```
benchmark
|- Cpp
    |- Savina
        |- src
           |- concurrency
              |-Banking.lf         
              |- ...
           |- micro
              |- PingPong.lf
              |- ...
           |- parallelism
              |- MatMul.lf
              |- MatMul
                 |- MatMul.cmake
                 |- MatMulCommon.hh
                 |- MatMulCommon.cc
              |- ...
```

**Comment by lhstrh** [comment]
@mattchorlian have these changes been implemented in the `c-benchmarks` branch? If so, is that branch ready to merge?

**Comment by mattchorlian** [comment]
@lhstrh yes the c-benchmarks branch has this directory structure and I believe it is ready to merge.

**Comment by cmnrd** [comment]
With #406 merged, this is resolved on master
