### ISSUE TITLE
Multiport connection is not displayed if width is unknown

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#421]
Consider the following C++ program:
```
target Cpp;

reactor Node(width: size_t(4)) {
    input[width] in: void
    output[width] out: void
}

main reactor {
    node = new Node(width={=4=});
    node.out -> node.in;
}
```
The generated diagram looks like this:
![DFT](https://user-images.githubusercontent.com/6460123/126490025-e29ab13f-fa05-48bb-99c6-060e99df6cfa.png)

The compiler is not able to infer the width of the multiports due to the use of `{==}`. However, the diagram should still display the connection as a normal multiport connection.

**Comment by edwardalee** [comment]
This is fixed in PR #428.
