### ISSUE TITLE
Replace `LF_MAIN_TARGET` with `LF_MAIN_REACTOR` in the generated CMakeLists.txt

### ISSUE THREAD

**Issue by Soroosh129** [icyphy/lingua-franca#429]
Currently, in the C and C++ targets, we use the variable `LF_MAIN_TARGET` in the generated `CMakeLists.txt` as the name of the CMake binary target (i.e., the name of the main reactor). This name will be the name of the produced executable, as per CMake's [specification](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#id15).

The `LF_MAIN_TARGET` can also conveniently be used in the `cmake-include` file, as explained [here](https://github.com/icyphy/lingua-franca/wiki/Writing-Reactors-in-C#the-c-target-specification).

@edwardalee pointed out that `LF_MAIN_TARGET` is problematic since target has a different meaning in Lingua Franca. I agree that this is problematic. As @edwardalee proposed, we should rename this to `LF_MAIN_REACTOR`.

I think to avoid confusion, it is better if we make this change at the same time for both the C and the C++ target.

**Comment by cmnrd** [comment]
This would be a drastic non-backward compatible change as external code relies on this variable name. 

While I see how the double use of 'target' can be confusing, I don't think that renaming the variable would help to make the cmake code any clearer. 'target' is a commonly used concept in cmake and most cmake users will know what it means. The cmake code that needs to be provided in the include file, will usually contain code like this:
```
target_include_directories(${LF_MAIN_TARGET} path/to/external/include)
target_link_libraries(${LF_MAIN_TARGET} ${CMAKE_THREAD_LIBS_INIT})
```
In this code, the functions `target_include_directories` or `target_link_libraries` expect a _target_ as first argument. In my opinion, the current name `LF_MAIN_TARGET` makes it absolutely clear that it represents a target and can be used in this context. I think that replacing this with `LF_MAIN_REACTOR` makes the code less readable, as cmake does not know about reactors, and it would be unclear which 'type' the variable has.

**Comment by cmnrd** [comment]
We decided to leave it at `LF_MAIN_TARGET` in today's LF meeting.
