### ISSUE TITLE
org.icyphy.linguafranca.diagram has build errors concerning EdgeStraighteningStrategy 

### ISSUE THREAD

**Issue by cxbrooks** [icyphy/lingua-franca#43]
In org.icyphy.linguafranca.diagram, after updating Eclipse with Kieler Lightweight Diagrams - Developer Resources and Examples from http://rtsys.informatik.uni-kiel.de/~kieler/updatesite/ and added all of Elk from https://build.eclipse.org/modeling/elk/updates/nightly, I'm still seeing build errors in 

org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis/LinguaFrancaSynthesis.xtend 

Description	Resource	Path	Location	Type
org.eclipse.elk.alg.layered.p4nodes.bk.EdgeStraighteningStrategy cannot be resolved to a type.	LinguaFrancaSynthesis.xtend	/org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis	line: 33 /org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis/LinguaFrancaSynthesis.xtend	Xtend Problem

and
The method or field EdgeStraighteningStrategy is undefined	LinguaFrancaSynthesis.xtend	/org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis	line: 81 /org.icyphy.linguafranca.diagram/src/org/icyphy/linguafranca/diagram/synthesis/LinguaFrancaSynthesis.xtend	Xtend Problem

the first is caused by 

`import org.eclipse.elk.alg.layered.p4nodes.bk.EdgeStraighteningStrategy`

the second by

```
rootNode.setLayoutOption(LayeredOptions.NODE_PLACEMENT_BK_EDGE_STRAIGHTENING, EdgeStraighteningStrategy.IMPROVE_STRAIGHTNESS)
```

Should these lines be commented out?

I updated xtext/README.md to include instructions for updating Eclipse with the Kieler plugins/features.    Perhaps I'm missing the correct steps?

**Comment by edwardalee** [comment]
I had the same problem.
I will forward the fix from Kiel, which worked for me…

Edward

———————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by cxbrooks** [comment]
It turns out that it is necessary to rebuild by hand to get the updated KIELER plug-ins.  Below are instructions:

* Choose Help -> Install New Software... from the menu bar
* In the Add.... entry, enter in  http://rtsys.informatik.uni-kiel.de/~kieler/updatesite/
* Hit the enter key
* Under Kieler Lightweight Diagrams:
* Select KIELER Lightweight Diagrams Generic Diagram View
* Select KIELER Lightweight	Diagrams Runtime
* Click Next
* Accept the licenses
* Accept the unsigned content
* Restart Eclipse
* Project -> Clean -> Clean
