### ISSUE TITLE
Enable multicore execution on Patmos/T-CREST

### ISSUE THREAD

**Issue by schoeberl** [icyphy/lingua-franca#44]
Map LF threads to cores either by providing a pthread emulation API in Patmos or have Patmos specific code in LF. In the initial version use plain, external shared memory for communication.

**Comment by lhstrh** [comment]
Update: the Patmos team is working on a Pthreads implementation. After this, our reactor runtime should work out-of-the-box.

**Comment by lhstrh** [comment]
The runtime is now fully supported via [t-crest/patmos-newlib](https://github.com/t-crest/patmos-newlib) and Patmos-specific code has been removed from the C runtime: https://github.com/icyphy/lingua-franca/commit/7ba87115d68e2b3a47dd92b85242a1df0622ffb3.
