### ISSUE TITLE
Invalid program triggers NullPointerException

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#460]
The following program triggers a NullPointerException:
```
target C;

main reactor {
  test = new Test();
}
```
While the program is invalid and compilation is expected to fail, the compiler should produce an actual error message instead of throwing a NullPointerException.

**Comment by edwardalee** [comment]
I am not able to replicate this. I don't an NPE. I get: "Couldn't resolve reference to ReactorDecl 'Test'."

**Comment by lhstrh** [comment]
@edwardalee: I think @cmnrd is using `lfc` and you're using Epoch? I can reproduce the error using `lfc`.

**Comment by lhstrh** [comment]
I've implemented a fix that now displays the following:
```
[marten@gen6 lingua-franca]$ bin/lfc -r ~/Downloads/test.lf
lfc: info: Jar file is missing or out-of-date; running Gradle.
lfc: info: Rebuild successful; forking off updated version of lfc.
lfc: warning: File 'test.lf' is not located in an 'src' directory.
lfc: warning: Adopting the current working directory as the package root.
lfc: error: Couldn't resolve reference to ReactorDecl 'Test'.
--> ../../../Downloads/test.lf:4:14
  |
3 | main reactor {
4 |   test = new Test();
  |              ^^^^ Couldn't resolve reference to ReactorDecl 'Test'.
  |
5 | }

lfc: fatal error: Aborting due to previous error
```
Note that this also addresses https://github.com/icyphy/lingua-franca/issues/459
