### ISSUE TITLE
Special type 'time' in LF grammar

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#53]
The LF grammar defines a special type `time` for the declaration of parameters. I found it suprising that this is limmeted to only paramters. To make the use of the `time` type more consistend, I propose to extend this notion to all places in the Grammar where types are used. This includes state but also ports and actions.

**Comment by edwardalee** [comment]
This sounds like a good idea to me.

Edward

---------
Edward A. Lee
EECS, UC Berkeley
eal@eecs.berkeley.edu
http://eecs.berkeley.edu/~eal

**Comment by lhstrh** [comment]
Isn't this already the case? The production for `Type: ID | CODE` matches
the literal `time`. Ports are not assigned default values, so no
distinction is made between values of target-language type and values of
time type there. The only place where I see this being an issue is with
state, which, like parameters, _requires_ a default value. We can easily
change that by swapping out `value=(Literal | ID)` for `value=TimeOrValue`
in the `State` production.

I'll take this as an action item.

**Comment by cmnrd** [comment]
Oh, right. So for ports and actions the backend should match on the literal 'time' and replace it with the correct type in the target language?

**Comment by lhstrh** [comment]
That’s what I had in mind, yes.

Marten
-- 

--
Marten Lohstroh, MSc. | Ph.D. Candidate
University of California | 545Q Cory Hall
Berkeley, CA 94720  | +1 510 282 9135

**Comment by lhstrh** [comment]
2c45866
