### ISSUE TITLE
Inaccurate errors wrt cycles in the precedence graph

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#59]
The following code below inappropriately reports "Reactions form a cycle, where every reaction depends on another reaction! - See error log for details"

```
target C;

reactor Foo(bar:int(42)) {
	state baz:int(42);
}

main reactor X {
	a = new Foo();
}
```

**Comment by edwardalee** [comment]
Ah, indeed!  This is because there are no “independent” reactions.  The error message should be improved.  I can do this...

Edward

---------
Edward A. Lee
EECS, UC Berkeley
eal@eecs.berkeley.edu
http://eecs.berkeley.edu/~eal

**Comment by edwardalee** [comment]
This now reports "Model has no reactions at all. Nothing to do."
