### ISSUE TITLE
Triggers on startup and shutdown actions are doubled.

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#60]
The logic in `generateReactor` of `GeneratorBase` creates new shutdown and startup actions if those are needed. It also adds an additional `VarRef` trigger to each reaction that triggers on 'shutdown' or 'startup' and references the shutdown or startup actions. However, the old triggers are not removed and thus there are two triggers referencing the same action. I am not sure about other target, but this causes problems in the C++ target.

**Comment by edwardalee** [comment]
Thanks for catching this (and fixing it!).

Edward

---------
Edward A. Lee
EECS, UC Berkeley
eal@eecs.berkeley.edu
http://eecs.berkeley.edu/~eal
