### ISSUE TITLE
Cpp target test failing: schedule.lf 

### ISSUE THREAD

**Issue by mew2ub** [icyphy/lingua-franca#74]
In my latest change to the LF grammar to allow properties to be assigned a "time" or a "literal" I uncovered what appears to be an unrelated problem with the Cpp target. If the schedule.lf main reactor is named "main" I get the following error:

> ERROR: make returns error code 2
> ERROR: make reports errors:
> Undefined symbols for architecture x86_64:
>   "_main", referenced from:
>      implicit entry/start for main executable
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [Schedule] Error 1
> make[1]: *** [CMakeFiles/Schedule.dir/all] Error 2
> make: *** [all] Error 2

The error does not appear and the test passes if the main reactor is named anything other than "main".

**Comment by mew2ub** [comment]
That's odd. I expected my last commit to fail on travis because the schedule.lf test was failing on my own computer, but it appears to have passed. Perhaps this is just a problem with my personal setup? Maybe this isn't a genuine issue. Can someone try replicating this?

**Comment by lhstrh** [comment]
According to the grammar, you cannot call a reactor `main` since it is a keyword; it would not compile.

**Comment by mew2ub** [comment]
The test file currently in the repo for [schedule.lf](https://github.com/icyphy/lingua-franca/blob/master/xtext/org.icyphy.linguafranca/src/test/Cpp/Schedule.lf) still has reactor named main. If this test should not compile, why is it passing?

**Comment by mew2ub** [comment]
Probably because it's named "Main" uppercase, is why it compiles. But I'm still not able to run it on my own machine.

**Comment by cmnrd** [comment]
What is your machine? Does it run MacOS by chance? On Linux all the tests pass, thats also why it works on Travis, since it only tests in a Linux machine.

**Comment by mew2ub** [comment]
Yes I'm running MacOS.

I don't think changing the test is a good idea and I don't think this issue is closed. The problem isn't that the test fails, the problem is that we have a valid LF program that fails on a common operating system. I think we should either prohibit "Main" as a reactor name in the grammar or we should get to the bottom of why this is failing on Mac.

**Comment by edwardalee** [comment]
I don't think this has anything to do with the OS. When the main reactor is named Main, the code generator does not generate a main function in the file main.cc. This looks like a code generator problem. I suggest looking at the diff between the code generated when the main reactor is named Main (which ought to be legal) and when it is named something else. They have very little in common.

**Comment by cxbrooks** [comment]
I’m not sure if this helps, but recall that sadly in the default, the macOS file system is case insensitive, case preserving, so it does not matter if the file is main.cc or Main.cc

_Christopher

(Sent from a device with a tiny keyboard)

**Comment by lhstrh** [comment]
Hmm, that sure does sound like a plausible explanation.

I propose we simply disallow reactors named `Main` in the validator.

**Comment by edwardalee** [comment]
Ah, I suspect that the code generator is generating main.cc, then also generating Main.cc, and the latter file overwrites the prior file.

**Comment by cmnrd** [comment]
Sorry, I did not intend to close the issue. GitHub auto closed it because I mentioned fix in my commit message.

Another simple solution would be to place all reactor code in a sub-directory so that it does not conflict with main.cc.

I am not against disalowing `Main` as a reactor name, but I'm not surer if that is the best way to go. My concern is that there are many other identifiers that cannot be used as reactor names and this is highly target depending. For instance I could name a C reactor `class` which I cannot do in C++. Apart from target langauge keywords there might be other variables defined in the enironment which also might clash with reactor names. This is beyond the control of LF.

**Comment by mew2ub** [comment]
A solution I've found for the TypeScript target is to automatically modify the name of each generated reactor with an underscore, so as not to conflict built in keywords. Maybe that would work for the `class` scenario you were describing?
