### ISSUE TITLE
Write conflicts between reactors and reactions

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#79]
When a connection of the form `c.x -> y` is made, there could potentially be a reaction that has `y` as an anti-dependency. In this case, I think, the connection should not be allowed (it could give rise to nondeterminism). We are currently not performing any such checks.

**Comment by edwardalee** [comment]
I don’t understand.  Don’t we just have to define the order in which contained reactors react relative to contained reactions? Can you give a concrete example that isn’t resolved by, say, invoking reactions before contained reactors?

Edward

---------
Edward A. Lee
EECS, UC Berkeley
eal@eecs.berkeley.edu
http://eecs.berkeley.edu/~eal

**Comment by lhstrh** [comment]
Reactors don't react; reactions do. In the construction of the precedence graph we abstract away reactors entirely. The only way to define order you suggest, is to introduce insert additional edges into the graph. We can do this (under the hood, at compile time) but this seems like a rather opaque solution to me. I think it's clearer to disallow it, just like we do with many-to-one connections between ports. In either case: right now, I think this situation remains unchecked. I'll add an example to illustrate my point, but I probably won't get to it before Friday.

**Comment by lhstrh** [comment]
Erroneous commit message on c77b688e. This is the issue that was fixed.
