### ISSUE TITLE
Build keeps choking on dependencies

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#81]
We keep getting messages like these on Travis:
```
Could not GET 'https://repo.maven.apache.org/maven2/org/eclipse/xtext/xtext-dev-bom/2.18.0/xtext-dev-bom-2.18.0.pom'. Received status code 403 from server: Forbidden
```
Usually restarting the build "fixes" the problem, but this is getting really annoying.

**Comment by cxbrooks** [comment]
The Triquetrum build was having problems like this once.

There was an Eclipse bug about this awhile ago: 

[Bug 492412 - Connection problems to external sources](https://bugs.eclipse.org/bugs/show_bug.cgi?id=492412) 

It looks to me like the solution was to use a local proxy.  Perhaps Travis has a local for maven?

**Comment by lhstrh** [comment]
These problems keep recurring occasionally. I doesn't look like Travis has a local mirror/proxy for maven, but it appears it can cache things, including Gradle, Maven, Composer and npm cache directories:
https://docs.travis-ci.com/user/caching/
I assume that enabling caching would mask some of these connection problems. In any case, it will speed up the build process on Travis. Let's give it a shot.
