### ISSUE TITLE
Fix all errors in C++ tests

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#84]
Currently some tests like StrideHierarchy.lf have errornous syntax. This is not an issue for running tests as thoose tests are not triggered, but the syntax should be fixed anyway. Alternatively, we could delete the unused tests.

**Comment by edwardalee** [comment]
One problem is that the Eclipse IDE seems to insist on compiling all .lf files it sees. Hence, errors will be reported.

**Comment by cmnrd** [comment]
This seems to be resolved
