### ISSUE TITLE
NPE in CGenerator

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#90]
The following code causes a null-pointer exception in `CGenerator.xtend:2230`:
```
target C;
reactor Relay {
	input r;
	output out:int;
	reaction (r) -> out {=
		set(out, r);
	=}
}
```
This could easily be fixed by adding null checks to the following statement:
`type.trim.endsWith('[]') || type.trim.endsWith('*')`
However, aren't types supposed to be required for ports in C?

**Comment by edwardalee** [comment]
I have augmented the validator to require types for the C and Cpp targets, but not for TypeScript.
