### ISSUE TITLE
Checking the presence of actions in C

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#91]
The following code does not compile because it `a_is_present` is not not defined:
```
target C;
main reactor Periodic(offset:time(0), period:time(500 msec)) {
    logical action a;
    reaction(startup, a) -> a {=
        if (!a_is_present) {
        	if (self->offset == 0)
        		printf("Hello World!\n");
        	else
        		schedule(a, self->offset, NULL);
        } else {
        	printf("Hello World!\n");
        	schedule(a, self->period, NULL);
		}
	=}
}
```

It should be possible to check the presence of actions in order to find out which one triggered it.

**Comment by lschuetze** [comment]
Just for the sake of curiosity. Would you not want to have both concerns (startup; and the setting of a periodic scheduling in the specific case) of probably unrelated events being separated into different reactors? Otherwise, it will ultimately lead to intermingled code handling different events.

```
target C;
main reactor Periodic(offset:time(0), period:time(500 msec)) {
    logical action a;
    reaction(startup) -> a {=
        if (self->offset == 0)	
        	printf("Hello World!\n");  
        else
        	schedule(a, self->offset, NULL);
	=}

    reaction(a) -> a {=
        printf("Hello World!\n");
        schedule(a, self->period, NULL);
	=}
}
```

**Comment by edwardalee** [comment]
I don't understand the question. First, the above example is better realized using a timer:
```
target C;
main reactor Periodic(offset:time(0), period:time(500 msec)) {
    timer t(offset, period);
    reaction(t) {=
         printf("Hello World!\n");
    =}
}
```
I think this example is meant to illustrate the fact that timers are (mostly) syntactic sugar. However, they aren't really, because the timer information is visible without parsing the target language, whereas that is not the case in your version.

As a general rule, reactions should belong to the same reactor when they share state. Otherwise, they should be in separate reactors.

**Comment by lschuetze** [comment]
I was mixing up reactors and reactions in the last comment. Using a timer totally removes the need to be able to react on a specific incoming event in this case. However, I originally wanted to highlight that the need to treat different events in a reaction each on its own may highlight that those events should be handled in different reactions altogether.

**Comment by edwardalee** [comment]
Ah yes, you are right. But in the original example, self->offset is not an event. It is a parameter.

**Comment by lhstrh** [comment]
The example I gave at the beginning of this thread illustrates the problem, but it does not illustrate meaningful use or the feature. It is not always possible to factor code into separate reactions; one might want to use mutual exclusivity of certain actions as a precondition for generating some output, for example. In that case, the reaction would need to be triggered by both reactions, and the code in the reaction body would have to check the presence of the respective reactions (only outputting if one of the triggers, not both, are present).

**Comment by edwardalee** [comment]
This appears to be have been fixed. I have added a test.
