### ISSUE TITLE
LF Grammar rule for startup triggers has buggy and unpredictable behavior

### ISSUE THREAD

**Issue by mew2ub** [icyphy/lingua-franca#92]
I think there's a problem with this line of the LF grammar regarding this TriggerRef rule.

```
TriggerRef:
    VarRef | startup?='startup' | shutdown?='shutdown';
```

I have an example (detailed below) in which a startup trigger will sometimes match the VarRef rule and sometimes match the startup?='startup' rule. This can produce bugs in code generation where the startup trigger is not assigned to a reaction. My theory for why this is happening is the xtext parser has undefined behavior for alternative statements ( statements with the "|" symbol for different cases) with overlapping matches. This TriggerRef parser rule can match the string 'startup' against a VarRef or against the literal 'startup'.

I propose eliminating the TriggerRef rule entirely and matching reaction triggers directly against VarRefs. The code generators can be modified from `if (trigger.startup) {` to `if (trigger.variable.name === 'startup') {`

Here's my example of the problem. I have a reactor with a startup trigger

`reaction (startup) {=
    ...
=}
`
that doesn't match the `startup?='startup'` case. It matches the `VarRef` case. Specifically when I run the TS code generator on the reactor with these print statements for debugging the issue

```
    println(trigger)
    if (trigger instanceof VarRef) {
         println(trigger.variable.name)
    }
```

The output is:

`org.icyphy.linguaFranca.impl.VarRefImpl@4437c81c (startup: false, shutdown: false)`
`startup`.

Even weirder, if I run the generator on a reactor with this redundant startup trigger:

`reaction (startup, startup) {=
    ...
=}
`

The output for the first startup trigger matches the `startup?='startup'` case:

`org.icyphy.linguaFranca.impl.TriggerRefImpl@39fcccc7 (startup: true, shutdown: false)`

and for the second matches the VarRef case:

`org.icyphy.linguaFranca.impl.VarRefImpl@4437c81c (startup: false, shutdown: false)`
`startup`.

**Comment by lhstrh** [comment]
I'm having a difficult time reproducing this. To the best of my knowledge, Xtext reports ambiguities in the grammar, and I see none reported.
Could you provide an LF source that exhibits the problem, as well as the line number in the code generator where the problem is exposed?

**Comment by lhstrh** [comment]
Regarding the fix that you propose: doing string matches in code generation is considered bad practice because if something changes in the grammar this may result in errors that could be masked by those string matches (i.e., the changes would not yield compilations errors in the code generator).

**Comment by mew2ub** [comment]
@lhstrh I just sent you an email. I can do the same for anyone else who wants to reproduce this.

I agree string matching in code generation is not an ideal way to go. But it's better than buggy code generation. I'm open to alternatives.

**Comment by lhstrh** [comment]
An update on this: the issue encountered by Matt is not a problem with the grammar (it is not ambiguous), but a problem with the code generator. At `GeneratorBase:265` a `TriggerRef` is replaced with a `VarRef` that points to a `Timer` that gets inserted into the AST. The idea behind this is that `startup` can be implemented using a timer for programs in which all reactors as instantiated and started up at the beginning of the execution of the program. With mutations, however, this may not necessarily be the case. In the TypeScript runtime, therefore, startup is _not_ implemented using a timer, but using an action, which is in conformance with the CyPhy paper. We should move the modifications to the AST to CGenerator.

**Comment by lhstrh** [comment]
I took a shot at factoring out the AST modifications, but the incompatibility is more significant. At `ReactionInstance:86`, for instance, there is the expectation of having a "startup timer." The TypeScriptGenerator trips over a NPE at this line if it bypasses the AST modifications that create the timer.

But why is it using creating an instantiation hierarchy (which is what these "instance" classes are meant to do) to begin with? Instantiation is done dynamically in TypeScript using the `new` keyword, so I don't see the need for doing this at compile time for this particular target. Am I missing something?

**Comment by lhstrh** [comment]
I propose that we bring the C target in compliance as well, and let is use an action to trigger startup.
That way, all the base code would remain reusable. The changes would be simple:
- change the AST modification is `GeneratorBase` such that an action is inserted rather than a trigger
- modify the runtime to not only call `__start_timers` at the beginning of execution, but also call something like `__schedule_startup_actions`. The contents of this latter function would not be all that different from what's currently in `__start_timers`.
